### ISSUE TITLE
ROIs manually labelled not plotting when removing overlapping pixels

### ISSUE THREAD

**Issue by mathildelpx** [MouseLand/suite2p#315] opened 2020-04-10 08:33 UTC
Hi,

I'm just reporting a small thing that is not really an issue but I think might be useful for other users and developers to know.

I'm using the latest version of suite2p (suite2p-0.7.1), but the files I will talk about were analyzed with the version suite2p-0.6.15.

I successfully run suite2p and manually labelled a lot more cells which you can see here in the GUI:

![image](https://user-images.githubusercontent.com/50573983/78975582-ab328a80-7b14-11ea-84ea-22835f027380.png)

When I tried to plot the ROIs masks outside of suite2p using the code suggested in the wiki, Igot only the ROIs detected by suite2p and none of the manually labelled ones:

````
stat = np.load('stat.npy', allow_pickle=True)
ops = np.load('ops.npy', allow_pickle=True)
ops = ops.item()
iscell = np.load('iscell.npy', allow_pickle=True)

cells_index = np.flatnonzero(iscell[:, 0])

im = np.zeros((ops['Ly'], ops['Lx']))

for i in cells_index:
    ypix = stat[i]['ypix'][~stat[i]['overlap']]
    xpix = stat[i]['xpix'][~stat[i]['overlap']]
    im[ypix, xpix] = i + 1

plt.imshow(im)
plt.show()
````
Resulting plot:
![ROI_masks_with_overlap](https://user-images.githubusercontent.com/50573983/78975874-5e02e880-7b15-11ea-9483-3f43a66322a1.png)

I then tried to plot it without removing the overlapping pixels, and this time it worked perfectly:
````
im = np.zeros((ops['Ly'], ops['Lx']))

for i in cells_index:
    ypix = stat[i]['ypix']
    xpix = stat[i]['xpix']
    im[ypix, xpix] = i + 1

plt.imshow(im)
plt.show()
````
Resulting plot:
![ROI_masks_without_overlap](https://user-images.githubusercontent.com/50573983/78975979-91457780-7b15-11ea-97ec-eddf6265c581.png)

The reason behind this is that `stat[i]['ypix'][~stat[i]['overlap']]` is empty for cells that were manually labelled.

**Comment by carsen-stringer** [comment] 2020-05-11 19:04
I've dug into this with the current version of the code and couldn't find a bug. Could you update to the latest github version and try to use that please?

**Comment by carsen-stringer** [comment] 2020-05-18 18:15
I'm going to close this since I couldn't reproduce it in the current version, please comment if there are still issues

**Closed by carsen-stringer** 2020-05-18 18:15 UTC
Labels: bug
