### ISSUE TITLE
Error preventing batch running of suite2p

### ISSUE THREAD

**Issue by tomsains** [MouseLand/suite2p#608] opened 2021-01-18 13:35 UTC
Hello,
I have recently installed the latest version of suite2p on my imac (OS 10.13.6) and I am getting an error right at the end of running suite2p, shortly after the combined view is created. Despite the "combined" output of suite2p still being generated this error prevents suite2p from moving onto the next dataset when batching. Since the error simply says "interrupted by error (not finished)" I am having trouble locating what might be going wrong. Has anyone come across this error before? The same batch runs fine on my ubuntu machine (same version of suite2p), so I am thinking this is an operating system specific error. Here is the complete log:

```

>>>ERROR<<<
OMP: Info #270: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
{'data_path': ['/Volumes/Meyer Group/thomas_sainsbury/Imaging/Raw_data/WT_GRAV_7_dpf/180530_WT_grav_h2b_gc6s_7dpf_f1_sa__00001'], 'subfolders': [], 'save_path0': '/Volumes/Meyer Group/thomas_sainsbury/Imaging/Raw_data/WT_GRAV_7_dpf/180530_WT_grav_h2b_gc6s_7dpf_f1_sa__00001', 'fast_disk': '/Volumes/Meyer Group/thomas_sainsbury/Imaging/Raw_data/WT_GRAV_7_dpf/180530_WT_grav_h2b_gc6s_7dpf_f1_sa__00001', 'input_format': 'tif'}
tif
** Found 1 tifs - converting to binary **
2016 frames of binary, time 509.42 sec.
4032 frames of binary, time 530.23 sec.
6048 frames of binary, time 549.19 sec.
8064 frames of binary, time 568.67 sec.
10080 frames of binary, time 588.76 sec.
12096 frames of binary, time 607.99 sec.
14112 frames of binary, time 627.49 sec.
16128 frames of binary, time 645.73 sec.
18144 frames of binary, time 665.46 sec.
20160 frames of binary, time 685.37 sec.
22176 frames of binary, time 704.74 sec.
24192 frames of binary, time 723.41 sec.
26208 frames of binary, time 742.36 sec.
28224 frames of binary, time 760.89 sec.
30240 frames of binary, time 775.94 sec.
32256 frames of binary, time 797.06 sec.
34272 frames of binary, time 813.90 sec.
36288 frames of binary, time 828.80 sec.
38304 frames of binary, time 844.79 sec.
40320 frames of binary, time 863.32 sec.
42336 frames of binary, time 880.48 sec.
44352 frames of binary, time 899.16 sec.
46368 frames of binary, time 917.90 sec.
48384 frames of binary, time 939.03 sec.
50400 frames of binary, time 955.03 sec.
52416 frames of binary, time 973.67 sec.
54432 frames of binary, time 991.60 sec.
56448 frames of binary, time 1011.40 sec.
58464 frames of binary, time 1028.21 sec.
60480 frames of binary, time 1046.91 sec.
62496 frames of binary, time 1069.55 sec.
64512 frames of binary, time 1087.26 sec.
66528 frames of binary, time 1108.13 sec.
68544 frames of binary, time 1123.09 sec.
70560 frames of binary, time 1138.76 sec.
72576 frames of binary, time 1159.02 sec.
74592 frames of binary, time 1179.59 sec.
76608 frames of binary, time 1198.58 sec.
78624 frames of binary, time 1216.95 sec.
80640 frames of binary, time 1234.33 sec.
82656 frames of binary, time 1252.18 sec.
84672 frames of binary, time 1270.17 sec.
86688 frames of binary, time 1288.68 sec.
88704 frames of binary, time 1308.57 sec.
90720 frames of binary, time 1326.22 sec.
92736 frames of binary, time 1344.01 sec.
94752 frames of binary, time 1364.45 sec.
96768 frames of binary, time 1382.58 sec.
98784 frames of binary, time 1402.50 sec.
100800 frames of binary, time 1421.62 sec.
102816 frames of binary, time 1439.75 sec.
104832 frames of binary, time 1456.55 sec.
106848 frames of binary, time 1478.70 sec.
108864 frames of binary, time 1499.38 sec.
110880 frames of binary, time 1517.23 sec.
112896 frames of binary, time 1533.54 sec.
114912 frames of binary, time 1549.70 sec.
116928 frames of binary, time 1569.12 sec.
118944 frames of binary, time 1585.66 sec.
120960 frames of binary, time 1603.60 sec.
122976 frames of binary, time 1624.56 sec.
124992 frames of binary, time 1644.61 sec.
127008 frames of binary, time 1662.14 sec.
129024 frames of binary, time 1682.23 sec.
131040 frames of binary, time 1711.12 sec.
133056 frames of binary, time 1727.16 sec.
135072 frames of binary, time 1743.89 sec.
137088 frames of binary, time 1763.95 sec.
139104 frames of binary, time 1778.96 sec.
141120 frames of binary, time 1799.08 sec.
143136 frames of binary, time 1816.14 sec.
145152 frames of binary, time 1839.18 sec.
147168 frames of binary, time 1858.04 sec.
149184 frames of binary, time 1875.86 sec.
151200 frames of binary, time 1896.11 sec.
153216 frames of binary, time 1913.41 sec.
155232 frames of binary, time 1936.35 sec.
157248 frames of binary, time 1953.53 sec.
159264 frames of binary, time 1973.93 sec.
161280 frames of binary, time 1992.77 sec.
163296 frames of binary, time 2008.85 sec.
165312 frames of binary, time 2027.75 sec.
167328 frames of binary, time 2048.97 sec.
169344 frames of binary, time 2065.65 sec.
171360 frames of binary, time 2086.62 sec.
173376 frames of binary, time 2102.46 sec.
175392 frames of binary, time 2120.98 sec.
177408 frames of binary, time 2139.49 sec.
179424 frames of binary, time 2160.97 sec.
181440 frames of binary, time 2178.59 sec.
183456 frames of binary, time 2201.49 sec.
185472 frames of binary, time 2218.78 sec.
187488 frames of binary, time 2240.82 sec.
189504 frames of binary, time 2257.33 sec.
191520 frames of binary, time 2280.28 sec.
193536 frames of binary, time 2298.56 sec.
195552 frames of binary, time 2321.46 sec.
197568 frames of binary, time 2336.58 sec.
199584 frames of binary, time 2358.33 sec.
201600 frames of binary, time 2378.18 sec.
203616 frames of binary, time 2398.07 sec.
205632 frames of binary, time 2417.30 sec.
207648 frames of binary, time 2435.34 sec.
time 2458.16 sec. Wrote 34920 frames per binary for 6 planes
>>>>>>>>>>>>>>>>>>>>> PLANE 0 <<<<<<<<<<<<<<<<<<<<<<
NOTE: not registered / registration forced with ops['do_registration']>1
      (no previous offsets to delete)
----------- REGISTRATION
registering 34920 frames
Reference frame, 8.11 sec.
Registered 2000/34920 in 23.37s
Registered 4000/34920 in 47.59s
Registered 6000/34920 in 71.77s
Registered 8000/34920 in 94.09s
Registered 10000/34920 in 117.65s
Registered 12000/34920 in 139.36s
Registered 14000/34920 in 161.46s
Registered 16000/34920 in 185.98s
Registered 18000/34920 in 209.05s
Registered 20000/34920 in 232.25s
Registered 22000/34920 in 253.21s
Registered 24000/34920 in 276.66s
Registered 26000/34920 in 300.06s
Registered 28000/34920 in 322.73s
Registered 30000/34920 in 343.88s
Registered 32000/34920 in 365.45s
Registered 34000/34920 in 387.74s
----------- Total 428.84 sec
Registration metrics, 9.25 sec.
NOTE: applying default /Users/MeyerLab/.suite2p/classifiers/classifier_user.npy
----------- ROI DETECTION
Binning movie in chunks of length 08
Binned movie [4278,238,230], 11.45 sec.
ROIs: 200, cost: 0.6931, time: 47.2451
ROIs: 400, cost: 0.6704, time: 52.8774
ROIs: 600, cost: 0.6562, time: 59.1685
ROIs: 800, cost: 0.6457, time: 65.9087
ROIs: 1000, cost: 0.6375, time: 72.9584
ROIs: 1200, cost: 0.6305, time: 80.8079
ROIs: 1340, cost: 0.6261, time: 88.8187
ROIs: 1368, cost: 0.6250, time: 96.4903
ROIs: 1373, cost: 0.6246, time: 103.8719
ROIs: 1373, cost: 0.6436, time: 114.6136
ROIs: 1373, cost: 0.6249, time: 119.5680
ROIs: 1373, cost: 0.6248, time: 123.6966
Found 1373 ROIs, 127.29 sec
After removing overlaps, 1267 ROIs remain
Masks made in 20.19 sec.
----------- Total 159.74 sec.
----------- EXTRACTION
Extracted fluorescence from 1267 ROIs in 34920 frames, 37.74 sec.
added enhanced mean image
----------- Total 44.94 sec.
----------- CLASSIFICATION
['npix_norm', 'compact', 'skew']
----------- Total 0.11 sec.
----------- SPIKE DECONVOLUTION
----------- Total 3.93 sec.
Plane 0 processed in 650.65 sec (can open in GUI).
>>>>>>>>>>>>>>>>>>>>> PLANE 1 <<<<<<<<<<<<<<<<<<<<<<
NOTE: not registered / registration forced with ops['do_registration']>1
      (no previous offsets to delete)
----------- REGISTRATION
registering 34920 frames
Reference frame, 8.89 sec.
Registered 2000/34920 in 20.67s
Registered 4000/34920 in 43.90s
Registered 6000/34920 in 68.12s
Registered 8000/34920 in 91.53s
Registered 10000/34920 in 112.95s
Registered 12000/34920 in 135.76s
Registered 14000/34920 in 157.49s
Registered 16000/34920 in 182.75s
Registered 18000/34920 in 205.11s
Registered 20000/34920 in 227.34s
Registered 22000/34920 in 249.88s
Registered 24000/34920 in 273.62s
Registered 26000/34920 in 296.21s
Registered 28000/34920 in 319.69s
Registered 30000/34920 in 343.55s
Registered 32000/34920 in 365.46s
Registered 34000/34920 in 388.69s
----------- Total 434.95 sec
Registration metrics, 8.06 sec.
NOTE: applying default /Users/MeyerLab/.suite2p/classifiers/classifier_user.npy
----------- ROI DETECTION
Binning movie in chunks of length 08
Binned movie [4278,236,230], 10.82 sec.
ROIs: 200, cost: 0.7032, time: 42.8760
ROIs: 400, cost: 0.6768, time: 48.0176
ROIs: 600, cost: 0.6605, time: 53.6512
ROIs: 800, cost: 0.6487, time: 59.8469
ROIs: 1000, cost: 0.6398, time: 66.2316
ROIs: 1200, cost: 0.6324, time: 73.4536
ROIs: 1275, cost: 0.6296, time: 80.1996
ROIs: 1287, cost: 0.6290, time: 86.5232
ROIs: 1287, cost: 0.6494, time: 95.9691
ROIs: 1287, cost: 0.6287, time: 100.2267
ROIs: 1287, cost: 0.6283, time: 103.8696
Found 1287 ROIs, 106.97 sec
After removing overlaps, 1199 ROIs remain
Masks made in 17.44 sec.
----------- Total 135.93 sec.
----------- EXTRACTION
Extracted fluorescence from 1199 ROIs in 34920 frames, 37.16 sec.
added enhanced mean image
----------- Total 44.01 sec.
----------- CLASSIFICATION
['npix_norm', 'compact', 'skew']
----------- Total 0.06 sec.
----------- SPIKE DECONVOLUTION
----------- Total 3.57 sec.
Plane 1 processed in 630.28 sec (can open in GUI).
>>>>>>>>>>>>>>>>>>>>> PLANE 2 <<<<<<<<<<<<<<<<<<<<<<
NOTE: not registered / registration forced with ops['do_registration']>1
      (no previous offsets to delete)
----------- REGISTRATION
registering 34920 frames
Reference frame, 8.55 sec.
Registered 2000/34920 in 21.97s
Registered 4000/34920 in 46.76s
Registered 6000/34920 in 72.86s
Registered 8000/34920 in 95.34s
Registered 10000/34920 in 119.61s
Registered 12000/34920 in 142.28s
Registered 14000/34920 in 165.86s
Registered 16000/34920 in 188.79s
Registered 18000/34920 in 213.66s
Registered 20000/34920 in 237.61s
Registered 22000/34920 in 259.29s
Registered 24000/34920 in 281.90s
Registered 26000/34920 in 303.99s
Registered 28000/34920 in 324.71s
Registered 30000/34920 in 347.81s
Registered 32000/34920 in 368.44s
Registered 34000/34920 in 389.60s
----------- Total 431.34 sec
Registration metrics, 8.55 sec.
NOTE: applying default /Users/MeyerLab/.suite2p/classifiers/classifier_user.npy
----------- ROI DETECTION
Binning movie in chunks of length 08
Binned movie [4278,242,238], 11.23 sec.
ROIs: 200, cost: 0.6963, time: 43.0984
ROIs: 400, cost: 0.6726, time: 48.3788
ROIs: 600, cost: 0.6573, time: 54.2470
ROIs: 800, cost: 0.6465, time: 60.6307
ROIs: 1000, cost: 0.6378, time: 67.6300
ROIs: 1200, cost: 0.6306, time: 75.1922
ROIs: 1334, cost: 0.6263, time: 82.3499
ROIs: 1348, cost: 0.6255, time: 89.0772
ROIs: 1348, cost: 0.6450, time: 99.1773
ROIs: 1348, cost: 0.6248, time: 103.8379
ROIs: 1348, cost: 0.6247, time: 107.5791
Found 1348 ROIs, 110.82 sec
After removing overlaps, 1277 ROIs remain
Masks made in 19.43 sec.
----------- Total 142.21 sec.
----------- EXTRACTION
Extracted fluorescence from 1277 ROIs in 34920 frames, 62.98 sec.
added enhanced mean image
----------- Total 71.86 sec.
----------- CLASSIFICATION
['npix_norm', 'compact', 'skew']
----------- Total 0.07 sec.
----------- SPIKE DECONVOLUTION
----------- Total 3.72 sec.
Plane 2 processed in 663.93 sec (can open in GUI).
>>>>>>>>>>>>>>>>>>>>> PLANE 3 <<<<<<<<<<<<<<<<<<<<<<
NOTE: not registered / registration forced with ops['do_registration']>1
      (no previous offsets to delete)
----------- REGISTRATION
registering 34920 frames
Reference frame, 8.17 sec.
Registered 2000/34920 in 22.23s
Registered 4000/34920 in 46.06s
Registered 6000/34920 in 69.42s
Registered 8000/34920 in 94.86s
Registered 10000/34920 in 117.24s
Registered 12000/34920 in 140.46s
Registered 14000/34920 in 163.22s
Registered 16000/34920 in 186.86s
Registered 18000/34920 in 208.68s
Registered 20000/34920 in 231.29s
Registered 22000/34920 in 252.99s
Registered 24000/34920 in 274.69s
Registered 26000/34920 in 297.15s
Registered 28000/34920 in 320.10s
Registered 30000/34920 in 341.71s
Registered 32000/34920 in 363.77s
Registered 34000/34920 in 384.91s
----------- Total 425.37 sec
Registration metrics, 8.57 sec.
NOTE: applying default /Users/MeyerLab/.suite2p/classifiers/classifier_user.npy
----------- ROI DETECTION
Binning movie in chunks of length 08
Binned movie [4278,240,234], 11.02 sec.
ROIs: 200, cost: 0.6936, time: 42.5193
ROIs: 400, cost: 0.6726, time: 47.7377
ROIs: 600, cost: 0.6586, time: 53.4469
ROIs: 800, cost: 0.6480, time: 59.5430
ROIs: 1000, cost: 0.6394, time: 66.5155
ROIs: 1200, cost: 0.6320, time: 73.8943
ROIs: 1250, cost: 0.6301, time: 80.4154
ROIs: 1251, cost: 0.6299, time: 86.7578
ROIs: 1251, cost: 0.6467, time: 96.5749
ROIs: 1251, cost: 0.6284, time: 100.8641
ROIs: 1251, cost: 0.6282, time: 104.4070
Found 1251 ROIs, 107.50 sec
After removing overlaps, 1206 ROIs remain
Masks made in 17.16 sec.
----------- Total 136.36 sec.
----------- EXTRACTION
Extracted fluorescence from 1206 ROIs in 34920 frames, 58.22 sec.
added enhanced mean image
----------- Total 66.31 sec.
----------- CLASSIFICATION
['npix_norm', 'compact', 'skew']
----------- Total 0.05 sec.
----------- SPIKE DECONVOLUTION
----------- Total 3.42 sec.
Plane 3 processed in 645.18 sec (can open in GUI).
>>>>>>>>>>>>>>>>>>>>> PLANE 4 <<<<<<<<<<<<<<<<<<<<<<
NOTE: not registered / registration forced with ops['do_registration']>1
      (no previous offsets to delete)
----------- REGISTRATION
registering 34920 frames
Reference frame, 8.09 sec.
Registered 2000/34920 in 23.91s
Registered 4000/34920 in 46.96s
Registered 6000/34920 in 72.27s
Registered 8000/34920 in 95.32s
Registered 10000/34920 in 116.16s
Registered 12000/34920 in 137.60s
Registered 14000/34920 in 159.32s
Registered 16000/34920 in 182.17s
Registered 18000/34920 in 205.97s
Registered 20000/34920 in 227.62s
Registered 22000/34920 in 250.20s
Registered 24000/34920 in 275.49s
Registered 26000/34920 in 297.00s
Registered 28000/34920 in 318.53s
Registered 30000/34920 in 343.68s
Registered 32000/34920 in 367.17s
Registered 34000/34920 in 392.72s
----------- Total 438.76 sec
Registration metrics, 8.35 sec.
NOTE: applying default /Users/MeyerLab/.suite2p/classifiers/classifier_user.npy
----------- ROI DETECTION
Binning movie in chunks of length 08
Binned movie [4278,236,230], 17.75 sec.
ROIs: 200, cost: 0.6904, time: 40.3394
ROIs: 400, cost: 0.6712, time: 45.4123
ROIs: 600, cost: 0.6584, time: 51.0150
ROIs: 800, cost: 0.6486, time: 57.3085
ROIs: 1000, cost: 0.6406, time: 63.9627
ROIs: 1099, cost: 0.6369, time: 70.3457
ROIs: 1105, cost: 0.6365, time: 76.0789
ROIs: 1105, cost: 0.6499, time: 85.0347
ROIs: 1105, cost: 0.6342, time: 88.9760
ROIs: 1105, cost: 0.6341, time: 92.2171
Found 1105 ROIs, 94.97 sec
After removing overlaps, 1078 ROIs remain
Masks made in 14.98 sec.
----------- Total 128.30 sec.
----------- EXTRACTION
Extracted fluorescence from 1078 ROIs in 34920 frames, 217.47 sec.
added enhanced mean image
----------- Total 224.34 sec.
----------- CLASSIFICATION
['npix_norm', 'compact', 'skew']
----------- Total 0.06 sec.
----------- SPIKE DECONVOLUTION
----------- Total 3.21 sec.
Plane 4 processed in 900.64 sec (can open in GUI).
>>>>>>>>>>>>>>>>>>>>> PLANE 5 <<<<<<<<<<<<<<<<<<<<<<
NOTE: not registered / registration forced with ops['do_registration']>1
      (no previous offsets to delete)
----------- REGISTRATION
registering 34920 frames
Reference frame, 8.44 sec.
Registered 2000/34920 in 47.81s
Registered 4000/34920 in 95.91s
Registered 6000/34920 in 141.11s
Registered 8000/34920 in 200.99s
Registered 10000/34920 in 248.45s
Registered 12000/34920 in 290.04s
Registered 14000/34920 in 347.76s
Registered 16000/34920 in 382.35s
Registered 18000/34920 in 429.32s
Registered 20000/34920 in 472.83s
Registered 22000/34920 in 508.65s
Registered 24000/34920 in 561.01s
Registered 26000/34920 in 597.96s
Registered 28000/34920 in 646.31s
Registered 30000/34920 in 688.21s
Registered 32000/34920 in 723.32s
Registered 34000/34920 in 781.87s
----------- Total 833.58 sec
Registration metrics, 6.94 sec.
NOTE: applying default /Users/MeyerLab/.suite2p/classifiers/classifier_user.npy
----------- ROI DETECTION
Binning movie in chunks of length 08
Binned movie [4234,208,208], 11.26 sec.
ROIs: 200, cost: 0.6712, time: 36.4516
ROIs: 400, cost: 0.6608, time: 40.2322
ROIs: 600, cost: 0.6501, time: 44.6146
ROIs: 800, cost: 0.6397, time: 49.7268
ROIs: 1000, cost: 0.6298, time: 55.0867
ROIs: 1198, cost: 0.6205, time: 60.9983
ROIs: 1263, cost: 0.6162, time: 66.3667
ROIs: 1283, cost: 0.6143, time: 71.4905
ROIs: 1297, cost: 0.6130, time: 76.6719
ROIs: 1297, cost: 0.6371, time: 83.8486
ROIs: 1297, cost: 0.6158, time: 87.5550
ROIs: 1297, cost: 0.6150, time: 90.4141
Found 1297 ROIs, 93.84 sec
After removing overlaps, 1219 ROIs remain
Masks made in 17.39 sec.
----------- Total 123.22 sec.
----------- EXTRACTION
Extracted fluorescence from 1219 ROIs in 34920 frames, 36.08 sec.
added enhanced mean image
----------- Total 50.65 sec.
----------- CLASSIFICATION
['npix_norm', 'compact', 'skew']
----------- Total 0.06 sec.
----------- SPIKE DECONVOLUTION
----------- Total 3.72 sec.
Plane 5 processed in 1022.56 sec (can open in GUI).
total = 6993.29 sec.
Creating combined view
appended plane 0 to combined view
appended plane 1 to combined view
appended plane 2 to combined view
appended plane 3 to combined view
appended plane 4 to combined view
appended plane 5 to combined view
TOTAL RUNTIME 7139.05 sec
Interrupted by error (not finished)



```

**Comment by carsen-stringer** [comment] 2021-01-21 15:42
is there an error that is being written to the anaconda terminal that might point to what the error is? If it's a windows error but not ubuntu it may that there is a path writing issue?

**Comment by SharonSheran** [comment] 2021-02-09 10:38
Hello,
I am having a similar error to that reported here. I installed the latest version of suite2p on my mac (OS 11.0.1) and I keep getting an error right at the end of running suite2p: "interrupted by error (not finished)". The output files are being generated in the desired folder but the GUI does not open at the end.  I would appreciate it if somebody could please help me identify the cause of the error?  
I have attached my complete log below for reference:

```
>>>ERROR<<<

OMP: Info #270: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
{'data_path': ['/Users/sherank/Python/suite2p/example'], 'subfolders': [], 'save_path0': '/Users/sherank/Python/suite2p/example', 'fast_disk': '/Users/sherank/Python/suite2p/example', 'input_format': 'tif'}
tif
** Found 1 tifs - converting to binary **
2000 frames of binary, time 2.06 sec.
4000 frames of binary, time 3.79 sec.
time 4.28 sec. Wrote 4500 frames per binary for 1 planes
`
`>>>>>>>>>>>>>>>>>>>>> PLANE 0 <<<<<<<<<<<<<<<<<<<<<<
NOTE: not registered / registration forced with ops['do_registration']>1
      (no previous offsets to delete)
----------- REGISTRATION
registering 4500 frames
Reference frame, 28.39 sec.
Registered 2000/4500 in 67.82s
Registered 4000/4500 in 137.21s
----------- Total 184.33 sec
Registration metrics, 19.31 sec.
NOTE: applying default /Users/sherank/.suite2p/classifiers/classifier_user.npy
----------- ROI DETECTION
Binning movie in chunks of length 10
Binned movie [450,319,552], 6.16 sec.
NOTE: estimated spatial scale ~6 pixels, time epochs 1.00, threshold 5.00 
0 ROIs, score=219.61
1000 ROIs, score=39.32
2000 ROIs, score=25.39
3000 ROIs, score=18.32
4000 ROIs, score=14.11
Found 5000 ROIs, 32.57 sec
After removing overlaps, 4575 ROIs remain
Masks made in 93.12 sec.
----------- Total 134.11 sec.
----------- EXTRACTION
Extracted fluorescence from 4575 ROIs in 4500 frames, 30.36 sec.
added enhanced mean image
----------- Total 33.59 sec.
----------- CLASSIFICATION
['npix_norm', 'compact', 'skew']
----------- Total 0.06 sec.
----------- SPIKE DECONVOLUTION
----------- Total 1.56 sec.
Plane 0 processed in 373.37 sec (can open in GUI).
total = 377.90 sec.
Saving in nwb format
root pynwb.file.NWBFile at 0x140463151714896
Fields:
  file_create_date: [datetime.datetime(2021, 2, 9, 11, 14, 32, 862350, tzinfo=tzlocal())]
  identifier: /Users/sherank/Python/suite2p/example
  session_description: suite2p_proc
  session_start_time: 2021-02-09 11:08:19.209708+01:00
  timestamps_reference_time: 2021-02-09 11:08:19.209708+01:00

TOTAL RUNTIME 379.47 sec
Interrupted by error (not finished)
```

**Comment by carsen-stringer** [comment] 2021-02-18 03:01
oh hmm I'm not really sure without more info, can you check if the terminal says anything while suite2p is running? errors I've seen with omp that crash things completely have been resolved with 
```
conda install nomkl
```

that warning message is coming from inside numba. you could also try upgrading numba.

**Comment by tomsains** [comment] 2021-02-19 11:30
Apologies for my late reply, I have been unable to access that computer (due to lockdown in the UK).
I will be in the lab next week. I will try these suggestions and report back since others are also now reporting the same issue.

**Comment by tomsains** [comment] 2021-02-19 14:32
I managed to access the computer:

installing nomkl resulted in a number of conflicts, which conda was unable to resolve:

```
(suite2p) Thomas-Sainsburys-iMac:~ MeyerLab$ conda install nomkl
 
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - h5py -> python[version='<3']
  - matplotlib-base -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0']
  - numpy[version='>=1.16'] -> python[version='>=3.5,<3.6.0a0']

Your python: python[version='>=3.7']

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.
```
(followed by many more lines of conflicted versions)

And numba appears to be up to date, with:

`conda update numba`

returning already satisfied

**Comment by penguingiraffe2** [comment] 2021-03-17 14:24
Bumping this since I'm receiving similar issues preventing batch from GUI. 

Running on Mac OS 11.2.2 (20D80) 

for interest in time ran it on previously registered data. 

**GUI run log:** 
```
>>>ERROR<<<
OMP: Info #270: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
{'data_path': ['/Users/alexandergoldberg/Documents/AZD_Analysis/ARG02/ARG02_S/Stim/runT'], 'subfolders': [], 'save_path0': '/Users/alexandergoldberg/Documents/AZD_Analysis/ARG02/ARG02_S/Stim/runT', 'fast_disk': '/Users/alexandergoldberg/Documents/AZD_Analysis/ARG02/ARG02_S/Stim/runT', 'input_format': 'tif'}
FOUND BINARIES AND OPS IN ['/Users/alexandergoldberg/Documents/AZD_Analysis/ARG02/ARG02_S/Stim/runT/suite2p/plane0/ops.npy']
>>>>>>>>>>>>>>>>>>>>> PLANE 0 <<<<<<<<<<<<<<<<<<<<<<
NOTE: not running registration, plane already registered
binary path: /Users/alexandergoldberg/Documents/AZD_Analysis/ARG02/ARG02_S/Stim/runT/suite2p/plane0/data.bin
NOTE: applying default /Users/alexandergoldberg/.suite2p/classifiers/classifier_user.npy
----------- ROI DETECTION
Binning movie in chunks of length 21
Binned movie [230,512,512] in 5.75 sec.
Binned movie denoised (for cell detection only) in 4.50 sec.
>>>> CELLPOSE finding masks in max_proj / mean_img
!NOTE! ops['diameter'] set to 8.00 for cell detection with cellpose
>>>> using CPU
Running test snippet to check if MKL-DNN working
see https://pytorch.org/docs/stable/backends.html?highlight=mkl
** MKL version working - CPU version is sped up. **
processing 1 image(s)
time spent: running network 236.17s; flow+mask computation 4.17
estimated masks for 1 image(s) in 240.37 sec
>>>> TOTAL TIME 240.37 sec
>>>> 31 masks detected, median diameter = 6.86 
Detected 31 ROIs, 240.48 sec
----------- Total 251.18 sec.
----------- EXTRACTION
Masks created, 0.17 sec.
Extracted fluorescence from 31 ROIs in 5400 frames, 5.86 sec.
----------- Total 6.13 sec.
----------- CLASSIFICATION
['npix_norm', 'compact', 'skew']
----------- Total 0.13 sec.
----------- SPIKE DECONVOLUTION
----------- Total 0.01 sec.
Plane 0 processed in 257.45 sec (can open in GUI).
total = 257.61 sec.
TOTAL RUNTIME 257.61 sec
Interrupted by error (not finished)
```

**Log from Anaconda Terminal:** 
```

OMP: Info #270: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
loaded default ops
Running suite2p!
starting process
{'data_path': ['/Users/alexandergoldberg/Documents/AZD_Analysis/ARG02/ARG02_S/Stim/runT'], 'subfolders': [], 'save_path0': '/Users/alexandergoldberg/Documents/AZD_Analysis/ARG02/ARG02_S/Stim/runT', 'fast_disk': '/Users/alexandergoldberg/Documents/AZD_Analysis/ARG02/ARG02_S/Stim/runT', 'input_format': 'tif'}

```

**Comment by carsen-stringer** [comment] 2021-03-31 11:10
I'm sorry you'll have to run suite2p in a jupyter-notebook I guess to capture the error message, sorry I don't have a mac to test this on, the below should work from testing

```
from suite2p import run_s2p

ops = np.load('ops.npy', allow_pickle=True).item()
ops_out = run_s2p(ops=ops)
```

**Comment by penguingiraffe2** [comment] 2021-04-06 16:47
I'm actually not running into an error when running it from the jupyter-notebook. The error is only present when running from the GUI

**Comment by carsen-stringer** [comment] 2021-07-23 14:27
can you try
```
conda upgrade numba
```
we have stopped pinning old mkl versions which may help with this, check out the new environment file

**Comment by kayleigrace** [comment] 2021-08-10 01:05
Hi,

I've also started experiencing this bug on mac (OS 10.15.7) with suite2p v0.10.1. I ran conda upgrade numba and it didn't seem to change anything, and was also unsuccessful in installing nomkl. That being said, suite2p seems to be running nonetheless, and I've been able to access the GUI by dragging stat.npy onto it. 

Please let me know if I can provide any error codes to diagnose the problem

**Comment by generalciao** [comment] 2022-06-28 14:11
Looks like a typo in your command, should be "nomkl" not "nomlk". Does that
work?

conda install nomkl

It turns off MKL, as per:
https://stackoverflow.com/questions/66224879/what-is-the-nomkl-python-package-used-for

**Comment by markuspleijzier** [comment] 2022-06-29 10:31
I deleted the conda environment, made a new one, and ran `python -m pip install suite2p[all]`, followed by conda install nomkl and the error persists.

**Comment by carsen-stringer** [comment] 2023-05-14 02:55
I'm sorry we need some way of catching this error on Mac. I don't have a Mac so I would recommend instead writing a bash script that calls suite2p in a loop for example, that way it won't get stuck.

generally speaking I do not recommend people to be processing many recordings on their personal laptops, we also now have suite2p working in google colab.

**Closed by carsen-stringer** 2023-05-14 02:55 UTC
Labels: bug, GUI

**Comment by Zinon-Liu** [comment] 2024-07-29 20:32
I also encountered the similar error on Mac when I mistakenly installed nomkl and numba in the base enviornment. But then I installed them in the suite2p env and it was solved
