### ISSUE TITLE
Process data from the same FOV seprately after reg and ROI detection?

### ISSUE THREAD

**Issue by PhantomSpike** [MouseLand/suite2p#127] opened 2018-12-05 20:07 UTC
Hi,

Is it possible to process two recordings (e.g. stim1 and stim2) from the same FOV (area) in the following way:

1. Run the registration and ROI detection on the two recordings together i.e. find the exact same ROIs for stim1 and stim2 since they come from the same FOV (area)

2. Then run the cell, Neuropile, dF/F and deconvolution separately on the two stimuli so you end up with separate traces for these variables for stim 1 and stim2.

This was possible in the Matlab version of Suite2P where you would set in your make_db_xx script:

db(i).mouse_name    = 'Jose'; 
db(i).date          = 'area01'; 
db(i).expts         = [1 2]; 

Where '1' and '2' are folders which contain .tif files for stim1 and stim2 respectively collected one after the other in 'area01'.

This would then do exactly what I was describing above and give you separate traces in the output .mat file.

Is it possible to do the exact same thing in the Python Suite2P, either via the GUI or the jupyter run_pipeline notebook?

Thanks a lot!

Alex

**Comment by carsen-stringer** [comment] 2018-12-06 17:53
In the python we end up concatenating the folders together. I will add to the output files when the folder change happens (say at what frame) so you can separate them yourself, sorry we won't support separating them out. Doing the deconvolution all together is probably better because you'll have a better estimation of the baseline that is subtracted (depending on how long your expts are).

**Comment by carsen-stringer** [comment] 2018-12-11 21:47
I've added a new key in ops, 'frames_per_folder'. This will keep track of the number of frames in each of the subfolders that the pipeline finds (using 'look_one_level_down'=1).

**Comment by lachioma** [comment] 2018-12-13 17:19
I would also like to combine separate experiments with Suite2p in Python in the same way as it is possible in Matlab with db(i).expts = [1 2].

Maybe it is because I am not familiar with Python, but by trying to use 'subfolders' in the following way, I get an error:

```
db = {
      'data_path': ['J:/lachioma/Data/AL_180921_b/2018-11-06/'], # a list of folders with tiffs 
                                             # (or folder of folders with tiffs if look_one_level_down is True, or subfolders is not empty)
      'subfolders': ['47726', 
                     '47728'] # choose subfolders of 'data_path' to look in (optional)
    }

opsEnd=run_s2p(ops=ops,db=db)
```



> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-14-4aaa588e449c> in <module>()
>       1 for dbi in db:
> ----> 2     opsEnd=run_s2p(ops=ops,db=dbi)
> 
> C:\ProgramData\Anaconda3\lib\site-packages\suite2p\run_s2p.py in run_s2p(ops, db)
>      88     ops0 = default_ops()
>      89     ops = {**ops0, **ops}
> ---> 90     ops = {**ops, **db}
>      91     if 'save_path0' not in ops or len(ops['save_path0'])==0:
>      92         if ('h5py' in ops) and len(ops['h5py'])>0:
> 
> TypeError: 'str' object is not a mapping


So it seems that the script does not accept a list, but rather just a single string?

Thanks for any help

**Comment by carsen-stringer** [comment] 2018-12-13 22:12
I'm not able to reproduce this error (using [run_pipeline_batch.ipynb](http://localhost:8890/notebooks/jupyter/run_pipeline_batch.ipynb). Here's my db file

db = {
      'look_one_level_down': False, 
      'data_path': ['/media/carsen/DATA1/TIFFS/FR096/'], 
      'subfolders': ['7','8'], 
      'fast_disk': '/media/carsen/SSD/'
    }

Also try `pip install suite2p --upgrade` as I've recently updated the pip.

What are the `ops` that you set?

**Comment by PhantomSpike** [comment] 2018-12-14 18:13
Thanks @carsen-stringer , that makes sense. I will just split them post-hoc.

A related question, are you guys planning to implement some sort of tool within the Python SUite2P that will allow you to register and process recordings of the same area, same animal but different days? I think that would be very useful for many people in the imaging community. It is very important to be able to find the same cells from different days  if you look at learning for example. I think concatenating and running all the .tiff files from these different days together will be problematic because you can have changes in brightness, tissue distortions, changes in expression of the GCaMP, etc

**Comment by lachioma** [comment] 2018-12-17 14:33
> I'm not able to reproduce this error (using [run_pipeline_batch.ipynb](http://localhost:8890/notebooks/jupyter/run_pipeline_batch.ipynb). Here's my db file
> 
> db = {
> 'look_one_level_down': False,
> 'data_path': ['/media/carsen/DATA1/TIFFS/FR096/'],
> 'subfolders': ['7','8'],
> 'fast_disk': '/media/carsen/SSD/'
> }
> 
> Also try `pip install suite2p --upgrade` as I've recently updated the pip.
> 
> What are the `ops` that you set?

I updated suite2p as you suggested, but I'm still getting the same error:

---------------------------------------------------------------------------

> TypeError                                 Traceback (most recent call last)
> <ipython-input-27-4aaa588e449c> in <module>()
>       1 for dbi in db:
> ----> 2     opsEnd=run_s2p(ops=ops,db=dbi)
> 
> C:\ProgramData\Anaconda3\lib\site-packages\suite2p\run_s2p.py in run_s2p(ops, db)
>      91     ops0 = default_ops()
>      92     ops = {**ops0, **ops}
> ---> 93     ops = {**ops, **db}
>      94     if 'save_path0' not in ops or len(ops['save_path0'])==0:
>      95         if ('h5py' in ops) and len(ops['h5py'])>0:
> 
> TypeError: 'str' object is not a mapping

This is my `ops `:

```
ops = {
        # file paths
        'data_path': 'J:/lachioma/Data/AL_180921_b/2018-11-06/', # a list of folders with tiffs (or folder of folders with tiffs if look_one_level_down is True, or subfolders is not empty)
	'look_one_level_down': False, # whether to look in all subfolders when searching for tiffs
        'fast_disk': 'J:/lachioma/Temp_suite2P_python/', # used to store temporary binary file, defaults to save_path0 (set as a string NOT a list)
        'save_path0': 'J:/lachioma/Temp_suite2P_python/Output/', # stores results, defaults to first item in data_path
        'delete_bin': True, # whether to delete binary file after processing
        # main settings
        'nplanes' : 1, # each tiff has these many planes in sequence
        'nchannels' : 2, # each tiff has these many channels per plane
        'functional_chan' : 1, # this channel is used to extract functional ROIs (1-based)
        'diameter': 22, # this is the main parameter for cell detection, 2-dimensional if Y and X are different (e.g. [6 12])
        'tau':  2.0, # this is the main parameter for deconvolution
        'fs': 17.6/2,  # sampling rate (total across planes)
        # output settings
        'save_mat': True, # whether to save output as matlab files
        'combined': True, # combine multiple planes into a single result /single canvas for GUI
        # parallel settings
        'num_workers': 0, # 0 to select num_cores, -1 to disable parallelism, N to enforce value
        'num_workers_roi': -1, # 0 to select number of planes, -1 to disable parallelism, N to enforce value
        # registration settings
        'do_registration': True, # whether to register data
        'nimg_init': 200, # subsampled frames for finding reference image
        'batch_size': 200, # number of frames per batch
        'maxregshift': 0.1, # max allowed registration shift, as a fraction of frame max(width and height)
        'align_by_chan' : 2, # when multi-channel, you can align by non-functional channel (1-based)
        'reg_tif': False, # whether to save registered tiffs
        'subpixel' : 10, # precision of subpixel registration (1/subpixel steps)
        # cell detection settings
        'connected': True, # whether or not to keep ROIs fully connected (set to 0 for dendrites)
        'navg_frames_svd': 2500, # max number of binned frames for the SVD
        'nsvd_for_roi': 350, # max number of SVD components to keep for ROI detection
        'max_iterations': 20, # maximum number of iterations to do cell detection
        'ratio_neuropil': 6., # ratio between neuropil basis size and cell radius
        'ratio_neuropil_to_cell': 4, # minimum ratio between neuropil radius and cell radius
        'tile_factor': 1., # use finer (>1) or coarser (<1) tiles for neuropil estimation during cell detection
        'threshold_scaling': 1., # adjust the automatically determined threshold by this scalar multiplier
        'max_overlap': 0.75, # cells with more overlap than this get removed during triage, before refinement
        'inner_neuropil_radius': 6, # number of pixels to keep between ROI and neuropil donut
        'outer_neuropil_radius': np.inf, # maximum neuropil radius
        'min_neuropil_pixels': 400, # minimum number of pixels in the neuropil
        # deconvolution settings
        'baseline': 'maximin', # baselining mode
        'win_baseline': 60., # window for maximin
        'sig_baseline': 10., # smoothing constant for gaussian filter
        'prctile_baseline': 8.,# optional (whether to use a percentile baseline)
        'neucoeff': .7,  # neuropil coefficient
      }
```
Thanks again for any help

**Comment by marius10p** [comment] 2018-12-17 14:47
@PhantomSpike we are looking into options for multi-day registration, but it will be at least a couple of months before we have a high-quality solution. Meanwhile, you can export results to the Matlab multi-day GUI and match semi-automatically. Or you could just try concatenating tiffs to see what happens: if you have enough SNR, the nonrigid registration should take care of distortions, i.e. angle misalignments and smaller nonrigid changes. Changes in brightness or expression won't matter nearly as much as distortions do.

**Comment by carsen-stringer** [comment] 2018-12-17 15:08
@lachioma Ah I think see your problem, your 'data_path' is a string not a list. Try saying `'data_path'=['path']`. Let me know if that still doesn't fix things.

**Comment by lachioma** [comment] 2018-12-17 17:40
> @lachioma Ah I think see your problem, your 'data_path' is a string not a list. Try saying `'data_path'=['path']`. Let me know if that still doesn't fix things.

@carsen-stringer  Unfortunately it still does not work, same error. 
I also tried to
- set `fast_disk` and `save_path0` to `[]`
- run Jupiter as administrator
- run the code using Spyder (as administrator) 
- move the files to a local folder in the main drive (C:) and make sure the paths are correct.

It's pretty odd...

**Comment by PhantomSpike** [comment] 2019-01-09 15:21
H @carsen-stringer ,

I have a small and easy to implement request. Do you think you can include the variable 'frames_per_folder' in the Matlab output .mat file? 

Some of our team members use Matlab for subsequent analysis afterwards and although it is present in ops.npy variable it is not possible to read it using the readNPY function.

Thanks a lot!

**Comment by carsen-stringer** [comment] 2019-01-09 15:52
Instead of loading ops.npy into matlab, I would recommend setting ops['save_mat']=1 and ops['combined']=1. This will create an "Fall.mat" in the "combined" folder that contains an ops that is loads into matlab. "frames_per_folder" is a field in this structure. Note the combined will concatenate mean images across planes.

**Comment by PhantomSpike** [comment] 2019-01-09 16:35
Hi,

Thanks for the quick reply. You are right, it is in the Fall.mat as ops.frames_per_folder. :)

**Comment by KnightyOwl** [comment] 2019-02-11 23:51
> @PhantomSpike we are looking into options for multi-day registration, but it will be at least a couple of months before we have a high-quality solution. Meanwhile, you can export results to the Matlab multi-day GUI and match semi-automatically. Or you could just try concatenating tiffs to see what happens: if you have enough SNR, the nonrigid registration should take care of distortions, i.e. angle misalignments and smaller nonrigid changes. Changes in brightness or expression won't matter nearly as much as distortions do.

Hi, I have a follow-up issue following this suggestion. I concatenated two different sessions from same FOV, but may be slightly different x,y,z since it was recorded in two different days. However, I found the fluoresence traces value became around 16000 and hence resulting in yielding a small delta F in this case...I tried turning on/off the non-rigid registration, seemed not helping much. Would that be possible to solve this issue?

**Comment by marius10p** [comment] 2019-02-12 00:27
Take a look at the registration metrics for your concatenated recording to see if the registration actually worked. I would be surprised if you don't need nonrigid registration.

If the fluorescence traces are jumping between days, that's not really something for Suite2p to fix. Try to look for the source of the discrepancy, like changes in the field of view, laser power or other acquisition parameters. There is baseline subtraction in the post-processing for spike deconvolution, and you can similarly do a baseline subtraction yourself if you would rather use the fluorescence rather than the spike deconvolved.

**Comment by carsen-stringer** [comment] 2019-02-27 00:21
I'm going to close this issue for now. Please let me know if you want it reopened. We also high-pass in time the frames (parameter ops['high_pass'] sets the window in frames for this) that should help with the changes in fluorescence during ROI detection.

**Closed by carsen-stringer** 2019-02-27 00:21 UTC

**Comment by ronan-dasilva** [comment] 2019-04-26 15:12
Hello!

I have a question about this issue: how can you align images from different trials when you are working with hdf5 files? Would I have to make individual folders with single h5 files or does it suffice to point out one folder with multiple files?

Thanks for helping out the noob!

Ronan

**Comment by carsen-stringer** [comment] 2019-04-26 15:17
You can point out a folder with multiple h5's by setting the h5path to one h5 file and then setting look_one_level_down=1 : https://github.com/MouseLand/suite2p/wiki/Input-format-and-supported-file-types#hdf5-files-and-sbx

Let me know if there are bugs in this, it is under tested

**Comment by ronan-dasilva** [comment] 2019-08-09 18:26
Hi!

I have been using the option to run multiple h5 files at once by pointing to one file and setting look_one_level_down=1 and I just learned about the ops['frames_per_folder'] key. It seems that the output ops.npy doesn't have this key when you run multiple h5 files.

Would it be possible to have the ops['frames_per_folder'] (or 'frames_per_h5'?) when running multiple h5 files?

Best!
