### ISSUE TITLE
Issue running multiple subsequent tiff stacks

### ISSUE THREAD

**Issue by tai-heinzerling** [MouseLand/suite2p#310] opened 2020-03-28 21:13 UTC
Almost every time I try to run suite2p on multiple tiff stacks that are supposed to be subsequent in time, I get this error right after it finishes registration: "ValueError: operands could not be broadcast together with shapes (44000,) (46000,) (44000,)". If I then force it to continue with ROI detection, it has another related error when trying to extract the traces: "IndexError: index 44000 is out of bounds for axis 1 with size 44000". My video is 46000 frames total, 24000 in the first tiff stack and 22000 in the second. But somewhere along the line it seems that one of the arrays has only 44000, so when it's trying to extract the rest of the frames, it's getting confused maybe? I have gotten it to work at least once, but I do not know what I did differently. One possible solution would be to concatenate my two tiff stacks before running suite2p, but I have not found a way to do that on my computer yet. If you have any ideas of how I can change my suite2p ops or concatenate my tiff stacks to make this work, I would be much appreciative.

**Comment by carsen-stringer** [comment] 2020-04-09 18:30
Sorry for the delayed response. Are these single plane tiffs? And you've put them in the same folder? Do you have a `bad_frames.npy` file? Can you tell me what line that ValueError occurs?

Also, in general it helps to delete the whole suite2p folder when rerunning to remove the old binary that may be messed up (you may already be doing this).

**Comment by tai-heinzerling** [comment] 2020-04-10 18:30
Hi Carsen,

Yes, these are single-plane tiffs and I put them in the same folder, so 
they are automatically detected as being consecutive videos. I do 
generally delete the whole suite2p folder before running. I do not see a 
bad_frames.npy file, however I should tell you that these two tiffs were 
recorded with a few minute break between them. So there will be a bit of 
a jump in activity partway through. I want to run them together so that 
I can compare the same cells in both recordings, so if there is a way to 
register which traces are from the same cells across the two videos 
after running suite2p, that would also solve my problem. I suppose it 
may also be important for you to know that I have gotten it to work a 
couple times, even when it failed on those same files earlier. I have 
not been able to figure out any pattern in my settings that makes it 
work consistently. Below is the whole error message for one of the 
failed runs, but I do not know for sure if it always says the exact same 
thing when it fails.

>>> ERROR<<<
Traceback (most recent call last):

   File 
"C:\Users\dmc_lab\AppData\Local\conda\conda\envs\suite2p\lib\runpy.py", 
line 193, in _run_module_as_main

>>> ERROR<<<
     "__main__", mod_spec)

   File 
"C:\Users\dmc_lab\AppData\Local\conda\conda\envs\suite2p\lib\runpy.py", 
line 85, in _run_code

>>> ERROR<<<
     exec(code, run_globals)

   File 
"C:\Users\dmc_lab\AppData\Local\conda\conda\envs\suite2p\lib\site-packages\suite2p\__main__.py", 
line 62, in <module>

>>> ERROR<<<
     parse_arguments()

   File 
"C:\Users\dmc_lab\AppData\Local\conda\conda\envs\suite2p\lib\site-packages\suite2p\__main__.py", 
line 55, in parse_arguments

     run_s2p.run_s2p(ops, db)

   File 
"C:\Users\dmc_lab\AppData\Local\conda\conda\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", 
line 251, in run_s2p

>>> ERROR<<<
     ops1[ipl] = register.register_binary(ops1[ipl]) # register binary

   File 
"C:\Users\dmc_lab\AppData\Local\conda\conda\envs\suite2p\lib\site-packages\suite2p\registration\register.py", 
line 390, in register_binary

>>> ERROR<<<
     ops['yoff'] += offsets[0]

ValueError: operands could not be broadcast together with shapes 
(44000,) (46000,) (44000,)



Thanks for your help!

**Comment by carsen-stringer** [comment] 2020-04-11 15:06
for some reason nframes is wrong (which initializes ops['yoff']). Do both of your tiffs end with *.tif? And they make sense in terms of size (e.g. one is 24/22 * the size in GB of the other one)

when the binary file is made, how many frames does it say are in it? (it should print ~every 2000 frames, depending on your batch size)

**Comment by tai-heinzerling** [comment] 2020-04-11 15:55
Yes, they both end in .tif and the GB sizes make sense with the number 
of frames. (I also checked that they had the correct number by loading 
them in Fiji.) I have always seen the binary file have the correct 
number of frames, 46000 in this case. And the correct number of frames 
are also registered.

**Comment by carsen-stringer** [comment] 2020-04-12 14:21
You're running in the GUI? I'm sorry I'm not sure what the issue is still. Can you check one more thing for me? The ops1 file should save after the binary is made, can you load it and check that the number of frames is correct?

~~~~
import numpy as np
ops1 = np.load('suite2p/ops1.npy', allow_pickle=True)
print(ops1[0]['nframes'])
~~~~

**Comment by tai-heinzerling** [comment] 2020-04-13 17:50
I just checked one of the runs and yes, the binary had the correct 
number of frames. Maybe I will try running that set of files one more 
time, since it has been a while, and I will be more attentive to all we 
have discussed. If we can't figure it out though, it's not a huge deal. 
I have already run the two tiff stacks individually and started using 
that data to some extent.

**Comment by tai-heinzerling** [comment] 2020-04-13 20:55
After rerunning it today (yes, on the GUI), I still have the same issue. I double checked that my original tiff stacks had the correct number of frames and I see that both the binary and saved reg_tif files have the correct number of frames. I'm attaching a text version of my ops.npy and run.txt files, but I don't think they will provide you with any new information unfortunately.

[run.log](https://github.com/MouseLand/suite2p/files/4471789/run.log)
[ops1txt.txt](https://github.com/MouseLand/suite2p/files/4471815/ops1txt.txt)

**Comment by carsen-stringer** [comment] 2020-05-01 15:28
I'm a bit confused by your ops1, it has all the info in there, like it ran all the way through. when you reran it doesn't seem like you deleted the folder?

**Comment by tai-heinzerling** [comment] 2020-05-01 17:03
Could that be because I loaded a previously-used ops file so that I didn't have to type all the ops in?

To be honest, I am actually phasing out of research this month, so I will not be using suite2p anymore. I could imagine others in my lab wanting to do this in the future, so it would be great if we could figure it out; but it's not a high priority for me.

**Comment by carsen-stringer** [comment] 2020-05-10 17:17
yeah I think that's the problem, I'll close this for now but happy to debug with your lab members if they need to

**Closed by carsen-stringer** 2020-05-10 17:17 UTC
