### ISSUE TITLE
Visualisation issues in the ROI window after running detection

### ISSUE THREAD

**Issue by MARGINMB** [MouseLand/suite2p#965] opened 2023-05-19 15:51 UTC
I am running suite2p now on some tif files and even though the entire analysis process seems to run fine, when I am supposed to visualize the file (after I see the message to close the initial window), I do not see anything in the ROI window. I have however files generated in the output. 
I am not sure why I can not visualize anything though and why the buttons on the left are frozen. 
I attach some error messages that I see in the xterm window (I am running VNC on the cluster).
Could you please help advising ?

![Screenshot 2023-05-19 at 16 05 04](https://github.com/MouseLand/suite2p/assets/16368584/c05b6d04-d3f8-458f-8842-689461f61d2d)
![Screenshot 2023-05-19 at 16 05 21](https://github.com/MouseLand/suite2p/assets/16368584/841cbec1-a57a-4dce-a5c8-1f814eaed695)
![Screenshot 2023-05-19 at 16 10 04](https://github.com/MouseLand/suite2p/assets/16368584/f83fb861-5309-4aa7-95e3-f3c7f246c491)

**Comment by carsen-stringer** [comment] 2023-05-24 20:54
duplicate of #953 ; this has now been fixed, please `pip install suite2p --upgrade`

**Closed by carsen-stringer** 2023-05-24 20:54 UTC

**Comment by MARGINMB** [comment] 2023-05-26 14:27
Great, it works now! Thank you!
