### ISSUE TITLE
BUG: Toggling ROIs off and on with spacebar causes a QGraphicsScene issue

### ISSUE THREAD

**Issue by landoskape** [MouseLand/suite2p#1028] opened 2023-08-29 14:40 UTC
### Describe the issue:

Toggling ROIs off and on does not work due to a bug in evaluating the state of the `ROIs_on` checkbox. 

### Reproduce the code example:

```python
suite2p
# (drag stat.npy file to suite2p)
# (press spacebar)
# (press spacebar)
```

The code that generates the warning (and failure to reload the ROIs) is here:
```
def ROIs_on(self, state):
        if state == QtCore.Qt.Checked:
            self.ops_plot["ROIs_on"] = True
            self.p1.addItem(self.color1)
            self.p2.addItem(self.color2)
        else:
            self.ops_plot["ROIs_on"] = False
            self.p1.removeItem(self.color1)
            self.p2.removeItem(self.color2)
        self.win.show()
        self.show()
```

`state` is an integer, with 0 corresponding to unchecked and 2 corresponding to checked. However, `QtCore.Qt.Checked` is an enum, so the if statement always evalutates to False.

This issue is fixed by converting `state` to an enum as follows: `QtCore.Qt.CheckState(state)`. I opened pull request #1029 to resolve it. 

### Warning message:

```shell
QGraphicsScene::removeItem: item 0x2dfc00f4060's scene (0x0) is different from this scene (0x2dfc015d070)
QGraphicsScene::removeItem: item 0x2dfc00fa900's scene (0x0) is different from this scene (0x2dfc015d070)
```
(An error isn't generated, but the code fails to replot the ROIs).

### Version information:

v0.14.2

### Context for the issue:

This issue prevents the user from being able to look at the images behind the ROIs while doing QC!

**Comment by landoskape** [comment] 2023-09-08 11:18
FYI - the same bug will cause an issue with the "roi_text" checkbox and the "zoom to ROI" checkbox.

**Comment by Andrianarivelo** [comment] 2023-11-01 16:05
exact same issue here !

**Comment by landoskape** [comment] 2023-11-01 16:55
@Andrianarivelo good to know it's just not an idiosyncrasy of my setup... but for the record if you want to get it to work before it's fixed, my PR (#1029) solves it! Only a few lines in one file need to be changed.

**Comment by Andrianarivelo** [comment] 2023-11-02 10:00
Which lines exactly do I have to change ?

**Comment by landoskape** [comment] 2023-11-02 11:06
[This page](https://github.com/MouseLand/suite2p/pull/1029/files) shows the lines. Alternatively you could clone from [my fork](https://github.com/landoskape/suite2p/tree/main) which is up to date with all the edits in the master/main branch. 

Then install using the [developers instructions](https://github.com/landoskape/suite2p/blob/main/README.md#installation-for-developers) in the README file. Note that you have to make sure to specify you're in a python 3.9 environment, so change the following line in the instructions:
```
# don't use this one:
# conda env create --name suite2p 

# use this instead:
conda env create --name suite2p python=3.9
```

**Comment by Andrianarivelo** [comment] 2023-11-02 11:27
Thanks, the issue is fixed for me :)

**Comment by landoskape** [comment] 2023-11-02 11:57
Woot!

**Comment by chriski777** [comment] 2023-11-05 16:52
Hi all, glad to hear that @landoskape's solution worked for you, @Andrianarivelo! Do y'all by chance both have Windows machines? We're having trouble replicating this on a Mac & Linux machine.

**Comment by Andrianarivelo** [comment] 2023-11-05 17:23
Yes I'm on windows, I also use Linux and don't have this issue.

**Comment by landoskape** [comment] 2023-11-06 12:44
I am on windows also

**Comment by chriski777** [comment] 2023-11-06 16:07
Thanks for your responses, everyone! @landoskape, ah no, it's not that. The problem was just not reproducible on a linux/Mac machine so just wanted to confirm it's machine-specific before validating your fix!

**Comment by chriski777** [comment] 2023-11-14 06:01
#1029 has been merged so now closing this issue. Thanks again, @landoskape, for the fix!

**Closed by chriski777** 2023-11-14 06:01 UTC
