### ISSUE TITLE
issues with jRCaMP acquisitions

### ISSUE THREAD

**Issue by MariangelaP** [MouseLand/suite2p#277] opened 2020-01-15 09:59 UTC
Hello,
I've been successfully using suite2p for GCaMP6 acquisitions, but I have recently started experiments with jRCaMP (barrel cortex layer 2-3) and I'm having troubles detecting ROIs. I must say that these preliminary exps are done on an anesthetized prep and activity (both spontaneous and evoked) is very very weak. My current frame rate is very low, between 1 and 5Hz. Here's a screenshot of what suite2p has found in a 200 frames acquisition at 1.5Hz.

<img width="618" alt="suite2p_rois" src="https://user-images.githubusercontent.com/31733932/72424177-d875d380-3785-11ea-981f-f26479b01cdb.PNG">

and here are the settings I've used:
<img width="621" alt="suite2p_settings" src="https://user-images.githubusercontent.com/31733932/72424212-e9bee000-3785-11ea-9c8d-2043529d93ca.PNG">

do you think the failure in detecting neurons comes from the very low activity levels, or is there anything you would definitely suggest changing in my settings?

many thanks!

**Comment by carsen-stringer** [comment] 2020-01-15 15:54
How many frames are you recording from? suite2p finds ROIs using activity so it will work better the longer the recording is. I would recommend trying the newer ROI detection algorithm by setting "sparse_mode" = 1. You could also try increasing tau to 2.0 if that doesn't help (that determines the bin size for ROI detection).

Here's another issue with RGECO with decent results that may be of use to you: https://github.com/MouseLand/suite2p/issues/233

**Comment by MariangelaP** [comment] 2020-01-16 08:36
Thanks for your help, Carsen.
This acquisition is very short, just 700 frames. I did try sparse_mode=1 while keeping tau as it was, but for some reason the algorithm gets it totally wrong (see below). If I increase tau, I get even more of the tiny ROIs.
<img width="511" alt="jrcamp_barrel_originalSettings_sparseMode1-results" src="https://user-images.githubusercontent.com/31733932/72506685-aeceb200-3842-11ea-9843-2614a12560cd.PNG">

I also tried running a jRCaMP on a very active field in an awake mouse. Sparse_mode is 1 in this case, see results below. The algorithm does alright, although it misses few cells as it detects them as enormous clusters of pixels including neuropil and other cells (see right panel). What would you suggest to overcome this issue? Max_overlap is set at 0.8. I remember there used to be a setting reinforcing the round shape of the ROIs. It was probably in the matlab version. Do we have anything similar in the python one? Or any other trick to suggest?

thanks again!

<img width="529" alt="jrcamp_hippo_diameter19_thrScaling0-5_MaxIterations50_SparseMode1_results" src="https://user-images.githubusercontent.com/31733932/72507120-901ceb00-3843-11ea-813e-39a30057ddfb.PNG">

**Comment by carsen-stringer** [comment] 2020-01-16 14:29
I think part of the problem is how short the acquisition is, there are not enough samples of the neurons firing for accurate estimation. If you want more smoothed/rounded ROIs then I'd stick to sparse_mode=0, but then you need to make sure you set the diameter in the right range of pixels - it looks pretty big here.

**Comment by carsen-stringer** [comment] 2020-03-01 01:46
I'm going to close this, we will add anatomical segmentation to suite2p in the near future as an option and that may help with this. also the dynamic range of those cells looks very small. if these are tiffs saved as floats, I'd recommend rescaling them and saving to int16 as I suggested [here](https://github.com/MouseLand/suite2p/issues/290#issuecomment-592967575)

**Closed by carsen-stringer** 2020-03-01 01:46 UTC
