### ISSUE TITLE
Multiple failures running test.py

### ISSUE THREAD

**Issue by Cumol** [MouseLand/suite2p#548] opened 2020-09-26 18:43 UTC
I was trying to figures out what the problem [here is](https://github.com/MouseLand/suite2p/issues/424#issuecomment-699492089) and did a clean install and ran the tests on the test data with following output:

I am on a Windows 10 machine

```
________________________________________________________________________________________________ test_tiff_reconstruction_from_binary_file _________________________________________________________________________________________________

test_ops = {'1Preg': False, 'align_by_chan': 1, 'allow_overlap': False, 'aspect': 1.0, ...}

    def test_tiff_reconstruction_from_binary_file(test_ops):
        """
        Tests to see if tif generated by tiff_to_binary and write_tiff matches test tif.
        """
        test_ops['tiff_list'] = ['input.tif']
        op = io.tiff_to_binary(test_ops)
        output_data = get_binary_file_data(op)
        # Make sure data in matrix is nonnegative
        assert np.all(output_data >= 0)
        fname = io.generate_tiff_filename(
            functional_chan=op['functional_chan'],
            align_by_chan=op['align_by_chan'],
            save_path=op['save_path'],
            k=0,
            ichan=True
        )
        io.save_tiff(output_data, fname=fname)
        reconstructed_tiff_data = imread(
            str(Path(test_ops['save_path0']).joinpath('suite2p/plane0/reg_tif/file000_chan0.tif'))
        )
        # Compare to our test data
        prior_data = imread(
            str(Path(test_ops['data_path'][0]).joinpath('1plane1chan/suite2p/test_write_tiff.tif'))
        )
>       assert np.array_equal(reconstructed_tiff_data, prior_data)
E       assert False
E        +  where False = <function array_equal at 0x0000021B26E31AF8>(array([[17419, 16798, 17359, ..., 16303, 16599, 16836],\n       [16485, 16419, 16185, ..., 16830, 16576, 16380],\n      ... [16449, 18001, 16308, ..., 16376, 16613, 17160],\n       [16397, 16393, 16282, ..., 16875, 16649, 17307]], dtype=int16), array([[[17419, 16798, 17359, ..., 16303, 16599, 16836],\n        [16485, 16419, 16185, ..., 16830, 16576, 16380],\n    ...17169, 16806, 17213, ..., 18657, 17320, 17852],\n        [17371, 17063, 16393, ..., 16529, 16294, 16966]]], dtype=int16))
E        +    where <function array_equal at 0x0000021B26E31AF8> = np.array_equal

tests\regression\test_io_pipeline.py:35: AssertionError
----------------------------------------------------------------------------------------------------------- Captured stdout call -----------------------------------------------------------------------------------------------------------
tif
** Found 1 tifs - converting to binary **
___________________________________________________________________________________________________ test_register_binary_do_bidi_output ____________________________________________________________________________________________________

test_ops = {'1Preg': False, 'Lx': 404, 'Ly': 360, 'align_by_chan': 1, ...}

    def test_register_binary_do_bidi_output(test_ops):
        """
        Regression test that checks the output of register_binary given the `input.tif` with the bidiphase,
        """
        test_ops['do_bidiphase'] = True
        check_registration_output(
            test_ops, (404, 360),
            test_ops['data_path'][0].joinpath('registration/bidi_shift_input.tif'),
            [str(Path(test_ops['save_path0']).joinpath('reg_tif/file000_chan0.tif'))],
>           [str(Path(test_ops['data_path'][0]).joinpath('registration/regression_bidi_output.tif'))]
        )

tests\regression\test_registration_pipeline.py:78:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

op = {'1Preg': False, 'Lx': 404, 'Ly': 360, 'align_by_chan': 1, ...}, dimensions = (404, 360), input_path = WindowsPath('data/test_data/registration/bidi_shift_input.tif')
reg_output_path_list = ['C:\\Users\\Dr. Siemens\\AppData\\Local\\Temp\\pytest-of-DrSiemens\\pytest-3\\test_register_binary_do_bidi_o0\\reg_tif\\file000_chan0.tif']
output_path_list = ['data\\test_data\\registration\\regression_bidi_output.tif']

    def check_registration_output(op, dimensions, input_path, reg_output_path_list, output_path_list):
        ops = prepare_for_registration(
            op, input_path, dimensions
        )
        reg_ops = []
        npl = op['nplanes']
        for i in range(npl):
            curr_op = register_binary(ops[i])
            registered_data = imread(reg_output_path_list[i*npl])
            output_check = imread(output_path_list[i*npl])
>           assert np.array_equal(registered_data, output_check)
E           assert False
E            +  where False = <function array_equal at 0x0000021B26E31AF8>(array([[17714, 16402, 15995, ..., 17270, 18572, 17432],\n       [16644, 16951, 17429, ..., 17275, 17487, 16757],\n      ... [16888, 16587, 16401, ..., 16285, 17186, 17129],\n       [17428, 16818, 17211, ..., 16332, 16622, 16836]], dtype=int16), array([[[17714, 16402, 15995, ..., 17270, 18572, 17432],\n        [16644, 16951, 17429, ..., 17275, 17487, 16757],\n    ...17060, 16928, 16920, ..., 18051, 17466, 17611],\n        [17684, 17278, 16862, ..., 16923, 16606, 16475]]], dtype=int16))
E            +    where <function array_equal at 0x0000021B26E31AF8> = np.array_equal

tests\regression\test_registration_pipeline.py:60: AssertionError
----------------------------------------------------------------------------------------------------------- Captured stdout call -----------------------------------------------------------------------------------------------------------
registering 500 frames
NOTE: estimated bidiphase offset from data: -3 pixels
Reference frame, 20.65 sec.
_______________________________________________________________________________________________ test_register_binary_rigid_registration_only _______________________________________________________________________________________________

test_ops = {'1Preg': False, 'Lx': 256, 'Ly': 256, 'align_by_chan': 1, ...}

    def test_register_binary_rigid_registration_only(test_ops):
        """
        Tests that register_binary works for a dataset that only has rigid shifts.
        """
        test_ops['nonrigid'] = False
        op = prepare_for_registration(
            test_ops,
            test_ops['data_path'][0].joinpath('registration/rigid_registration_test_data.tif'),
            (256, 256),
        )[0]
        op = register_binary(op)
        registered_data = imread(str(Path(op['save_path']).joinpath('reg_tif/file000_chan0.tif')))
        # Make sure registered_data is identical across frames
>       check_data = np.repeat(registered_data[0, :, :][np.newaxis, :, :], 500, axis=0)
E       IndexError: too many indices for array

tests\regression\test_registration_pipeline.py:95: IndexError
----------------------------------------------------------------------------------------------------------- Captured stdout call -----------------------------------------------------------------------------------------------------------
registering 500 frames
Reference frame, 9.04 sec.
__________________________________________________________________________________________________ test_cli_reg_metrics_runs_with_output ___________________________________________________________________________________________________

capfd = <_pytest.capture.CaptureFixture object at 0x0000021B0190CC08>, tmpdir = local('C:\\Users\\Dr. Siemens\\AppData\\Local\\Temp\\pytest-of-DrSiemens\\pytest-3\\test_cli_reg_metrics_runs_with0')

    def test_cli_reg_metrics_runs_with_output(capfd, tmpdir):
        os.system(f'reg_metrics data/test_data/ --tiff_list input_1500.tif --do_registration 2 --save_path0 {tmpdir}')
        captured = capfd.readouterr()
>       assert captured.out
E       AssertionError: assert ''
E        +  where '' = CaptureResult(out='', err='c:\\users\\dr. siemens\\anaconda3\\envs\\suite2p\\lib\\site-packages\\numba\\np\\ufunc\\par...cognized arguments: Siemens\\AppData\\Local\\Temp\\pytest-of-DrSiemens\\pytest-3\\test_cli_reg_metrics_runs_with0\r\n').out

tests\smoke\test_cli.py:45: AssertionError
============================================================================================================= warnings summary =============================================================================================================
tests/regression/test_full_pipeline.py::test_mesoscan_2plane_2z
tests/regression/test_full_pipeline.py::test_mesoscan_2plane_2z
tests/regression/test_full_pipeline.py::test_mesoscan_2plane_2z
tests/regression/test_full_pipeline.py::test_mesoscan_2plane_2z
  c:\users\dr. siemens\suite2p\suite2p\registration\register.py:182: UserWarning: number of frames is below 200, unpredictable behaviors may occur.
    warn('number of frames is below 200, unpredictable behaviors may occur.')

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================================================================================= short test summary info ==========================================================================================================
FAILED tests/regression/test_full_pipeline.py::test_1plane_1chan_with_batches_metrics_and_exported_to_nwb_format - NameError: name 'NWBHDF5IO' is not defined
FAILED tests/regression/test_full_pipeline.py::test_2plane_2chan_with_batches - ValueError: operands could not be broadcast together with shapes (375,256,256) (512,256)
FAILED tests/regression/test_io_pipeline.py::test_tiff_reconstruction_from_binary_file - assert False
FAILED tests/regression/test_registration_pipeline.py::test_register_binary_do_bidi_output - assert False
FAILED tests/regression/test_registration_pipeline.py::test_register_binary_rigid_registration_only - IndexError: too many indices for array
FAILED tests/smoke/test_cli.py::test_cli_reg_metrics_runs_with_output - AssertionError: assert ''
=========================================================================================== 6 failed, 26 passed, 4 warnings in 436.05s (0:07:16) ===========================================================================================

```

**Comment by nickdelgrosso** [comment] 2020-10-04 18:42
Hi @Cumol,

Thank you for this report.  It looks like there are a few different potential problems here, but it's hard to sort out the causes of them.  It looks like some packages are missing, and there may be differences in some test data.  

Could you please try creating a fresh conda environment and running the following in order and sharing the debug output again using the following lines:

```
git clone https://github.com/MouseLand/suite2p
cd suite2p
conda env remove -n suite2p
conda env create -f environment.yml
conda activate suite2p
pip install .[data,nwb]
dvc pull -r gdrive-travis
python setup.py test
```

Best wishes,

Nick

**Comment by Cumol** [comment] 2020-10-16 09:27
On Ubuntu 18.04 LTS

```
platform linux -- Python 3.7.9, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
PyQt5 5.9.2 -- Qt runtime 5.9.7 -- Qt compiled 5.9.6
rootdir: /home/generalubuntu/repos/suite2p
plugins: qt-3.3.0
collected 29 items                                                             

tests/test_io.py ....                                                    [ 13%]
tests/test_registration.py ...                                           [ 24%]
tests/test_version.py ...                                                [ 34%]
tests/regression/test_classification_pipeline.py .                       [ 37%]
tests/regression/test_detection_pipeline.py ..                           [ 44%]
tests/regression/test_extraction_pipeline.py ...                         [ 55%]
tests/regression/test_full_pipeline.py ..F.                              [ 68%]
tests/smoke/test_cli.py .......                                          [ 93%]
tests/smoke/test_gui.py .                                                [ 96%]
tests/smoke/test_run_s2p.py .                                            [100%]

=================================== FAILURES ===================================
__________________________ test_1plane_2chan_sourcery __________________________

test_ops = {'1Preg': False, 'align_by_chan': 1, 'allow_overlap': False, 'aspect': 1.0, ...}

    def test_1plane_2chan_sourcery(test_ops):
        """
        Tests for case with 1 plane and 2 channel.
        """
        test_ops.update({
            'nchannels': 2,
            'sparse_mode': 0,
            'tiff_list': ['input.tif'],
            'keep_movie_raw': True
        })
        suite2p.run_s2p(ops=test_ops)
        nplanes = test_ops['nplanes']
>       assert all(utils.check_output(
            output_root=test_ops['save_path0'],
            outputs_to_check=get_outputs_to_check(test_ops['nchannels']),
            test_data_dir=test_ops['data_path'][0].joinpath(f"{nplanes}plane{test_ops['nchannels']}chan/suite2p/"),
            nplanes=nplanes,
        ))
E       AssertionError: assert False
E        +  where False = all(<generator object check_output at 0x7f2cf30c5f50>)
E        +    where <generator object check_output at 0x7f2cf30c5f50> = <function check_output at 0x7f2cede8e9e0>(output_root='/tmp/pytest-of-generalubuntu/pytest-0/test_1plane_2chan_sourcery0', outputs_to_check=['F', 'Fneu', 'iscell', 'spks', 'stat', 'F_chan2', ...], test_data_dir=PosixPath('data/test_data/1plane2chan/suite2p'), nplanes=1)
E        +      where <function check_output at 0x7f2cede8e9e0> = utils.check_output
E        +      and   ['F', 'Fneu', 'iscell', 'spks', 'stat', 'F_chan2', ...] = get_outputs_to_check(2)
E        +      and   PosixPath('data/test_data/1plane2chan/suite2p') = <bound method PurePath.joinpath of PosixPath('data/test_data')>('1plane2chan/suite2p/')
E        +        where <bound method PurePath.joinpath of PosixPath('data/test_data')> = PosixPath('data/test_data').joinpath

tests/regression/test_full_pipeline.py:84: AssertionError
----------------------------- Captured stdout call -----------------------------
{}
tif
** Found 1 tifs - converting to binary **
time 2.53 sec. Wrote 250 frames per binary for 1 planes
>>>>>>>>>>>>>>>>>>>>> PLANE 0 <<<<<<<<<<<<<<<<<<<<<<
NOTE: not registered / registration forced with ops['do_registration']>1
      (no previous offsets to delete)
----------- REGISTRATION
registering 250 frames
Reference frame, 33.48 sec.
Registered second channel in 0.73 sec.
----------- Total 43.77 sec
NOTE: Applying builtin classifier at /home/generalubuntu/repos/suite2p/suite2p/classifiers/classifier.npy
----------- ROI DETECTION
Binning movie in chunks of length 10
Binned movie [25,356,400], 0.20 sec.
ROIs: 187, cost: 0.4422, time: 14.5833
ROIs: 283, cost: 0.4005, time: 22.3984
ROIs: 304, cost: 0.3926, time: 25.6340
ROIs: 307, cost: 0.3900, time: 27.3995
ROIs: 307, cost: 0.5907, time: 27.9619
ROIs: 307, cost: 0.5893, time: 30.4426
ROIs: 307, cost: 0.5872, time: 32.8042
Found 307 ROIs, 43.87 sec
After removing overlaps, 277 ROIs remain
Masks made in 5.20 sec.
----------- Total 55.46 sec.
----------- EXTRACTION
Extracted fluorescence from 277 ROIs in 250 frames, 0.47 sec.
Extracted fluorescence from 277 ROIs in 250 frames, 0.48 sec.
added enhanced mean image
----------- Total 7.08 sec.
----------- CLASSIFICATION
----------- Total 0.04 sec.
----------- SPIKE DECONVOLUTION
----------- Total 0.01 sec.
Plane 0 processed in 106.36 sec (can open in GUI).
total = 108.93 sec.
TOTAL RUNTIME 108.93 sec
=============================== warnings summary ===============================
suite2p/extraction/extract.py:148
  /home/generalubuntu/repos/suite2p/suite2p/extraction/extract.py:148: DeprecationWarning: invalid escape sequence \*
    """

tests/regression/test_full_pipeline.py::test_1plane_1chan_with_batches_metrics_and_exported_to_nwb_format
  /home/generalubuntu/anaconda3/envs/suite2p/lib/python3.7/site-packages/pynwb/file.py:753: UserWarning: Date is missing timezone information. Updating to local timezone.
    warn("Date is missing timezone information. Updating to local timezone.")

tests/regression/test_full_pipeline.py::test_1plane_1chan_with_batches_metrics_and_exported_to_nwb_format
  /home/generalubuntu/anaconda3/envs/suite2p/lib/python3.7/site-packages/hdmf/build/objectmapper.py:239: DtypeConversionWarning: Spec 'ImagingPlane/grid_spacing': Value with data type int64 is being converted to data type float64 (min specification: float32).
    warnings.warn(full_warning_msg, DtypeConversionWarning)

tests/regression/test_full_pipeline.py::test_mesoscan_2plane_2z
tests/regression/test_full_pipeline.py::test_mesoscan_2plane_2z
tests/regression/test_full_pipeline.py::test_mesoscan_2plane_2z
tests/regression/test_full_pipeline.py::test_mesoscan_2plane_2z
  /home/generalubuntu/repos/suite2p/suite2p/registration/register.py:182: UserWarning: number of frames is below 200, unpredictable behaviors may occur.
    warn('number of frames is below 200, unpredictable behaviors may occur.')

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ============================
FAILED tests/regression/test_full_pipeline.py::test_1plane_2chan_sourcery - A...
============= 1 failed, 28 passed, 7 warnings in 617.17s (0:10:17) =============

```

**Comment by Cumol** [comment] 2020-10-16 09:44
On Windows 10

```
================================================= test session starts =================================================
platform win32 -- Python 3.7.9, pytest-6.0.2, py-1.9.0, pluggy-0.13.1
PyQt5 5.9.2 -- Qt runtime 5.9.7 -- Qt compiled 5.9.6
rootdir: C:\Users\Dr. Siemens\suite2p
plugins: qt-3.3.0
collected 32 items

tests\test_io.py ....                                                                                            [ 12%]
tests\test_registration.py ...                                                                                   [ 21%]
tests\test_version.py ...                                                                                        [ 31%]
tests\regression\test_classification_pipeline.py .                                                               [ 34%]
tests\regression\test_detection_pipeline.py ..                                                                   [ 40%]
tests\regression\test_extraction_pipeline.py ...                                                                 [ 50%]
tests\regression\test_full_pipeline.py .F..                                                                      [ 62%]
tests\regression\test_io_pipeline.py F                                                                           [ 65%]
tests\regression\test_registration_pipeline.py FF                                                                [ 71%]
tests\smoke\test_cli.py .....F.                                                                                  [ 93%]
tests\smoke\test_gui.py .                                                                                        [ 96%]
tests\smoke\test_run_s2p.py .                                                                                    [100%]

====================================================== FAILURES =======================================================
___________________________________________ test_2plane_2chan_with_batches ____________________________________________

test_ops = {'1Preg': False, 'align_by_chan': 1, 'allow_overlap': False, 'aspect': 1.0, ...}

    def test_2plane_2chan_with_batches(test_ops):
        """
        Tests for case with 2 planes and 2 channels with multiple batches.  Runs twice to check for consistency.
        """
        for _ in range(2):
            ops = test_ops.copy()
            ops.update({
                'tiff_list': ['input_1500.tif'],
                'batch_size': 200,
                'nplanes': 2,
                'nchannels': 2,
                'reg_tif': True,
                'reg_tif_chan2': True,
            })
            nplanes = ops['nplanes']
            suite2p.run_s2p(ops=ops)
>           assert all(utils.check_output(
                output_root=ops['save_path0'],
                outputs_to_check=get_outputs_to_check(ops['nchannels']) + ['reg_tif', 'reg_tif_chan2'],
                test_data_dir=ops['data_path'][0].joinpath(f"{nplanes}plane{ops['nchannels']}chan1500/suite2p/"),
                nplanes=nplanes,
            ))

tests\regression\test_full_pipeline.py:64:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests\utils.py:85: in check_output
    get_list_of_output_data(outputs_to_check, output_root, i),
tests\utils.py:98: in compare_list_of_outputs
    yield np.allclose(data1, data2, rtol=r_tol, atol=a_tol)
..\Anaconda3\envs\suite2p\lib\site-packages\numpy\core\numeric.py:2423: in allclose
    res = all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))
..\Anaconda3\envs\suite2p\lib\site-packages\numpy\core\numeric.py:2524: in isclose
    return within_tol(x, y, atol, rtol)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

x = array([[[16828, 16752, 16857, ..., 16944, 16622, 17088],
        [17198, 17099, 16711, ..., 17065, 16853, 16749],
    ...17145, 16937, 16943, ..., 16873, 16611, 16452],
        [17056, 17095, 17004, ..., 16433, 16476, 16470]]], dtype=int16)
y = array([[16828., 16752., 16857., ..., 16944., 16622., 17088.],
       [17198., 17099., 16711., ..., 17065., 16853., 167...  [16604., 16657., 16541., ..., 16711., 17094., 17040.],
       [16391., 16458., 16711., ..., 16690., 17171., 17347.]])
atol = 0.05, rtol = 0.0001

    def within_tol(x, y, atol, rtol):
        with errstate(invalid='ignore'):
>           return less_equal(abs(x-y), atol + rtol * abs(y))
E           ValueError: operands could not be broadcast together with shapes (375,256,256) (512,256)

..\Anaconda3\envs\suite2p\lib\site-packages\numpy\core\numeric.py:2510: ValueError
------------------------------------------------ Captured stdout call -------------------------------------------------
{}
tif
** Found 1 tifs - converting to binary **
800 frames of binary, time 0.70 sec.
time 1.14 sec. Wrote 375 frames per binary for 2 planes
>>>>>>>>>>>>>>>>>>>>> PLANE 0 <<<<<<<<<<<<<<<<<<<<<<
NOTE: not registered / registration forced with ops['do_registration']>1
      (no previous offsets to delete)
----------- REGISTRATION
registering 375 frames
Reference frame, 8.70 sec.
Registered second channel in 0.88 sec.
----------- Total 14.64 sec
NOTE: Applying builtin classifier at C:\Users\Dr. Siemens\suite2p\suite2p\classifiers\classifier.npy
----------- ROI DETECTION
Binning movie in chunks of length 10
Binned movie [37,252,254], 0.19 sec.
NOTE: estimated spatial scale ~12 pixels, time epochs 1.00, threshold 10.00
0 ROIs, score=32.51
Found 81 ROIs, 1.51 sec
After removing overlaps, 81 ROIs remain
Masks made in 1.45 sec.
----------- Total 4.84 sec.
----------- EXTRACTION
Extracted fluorescence from 81 ROIs in 375 frames, 0.15 sec.
Extracted fluorescence from 81 ROIs in 375 frames, 0.15 sec.
added enhanced mean image
----------- Total 2.52 sec.
----------- CLASSIFICATION
----------- Total 0.03 sec.
----------- SPIKE DECONVOLUTION
----------- Total 0.00 sec.
Plane 0 processed in 22.05 sec (can open in GUI).
>>>>>>>>>>>>>>>>>>>>> PLANE 1 <<<<<<<<<<<<<<<<<<<<<<
NOTE: not registered / registration forced with ops['do_registration']>1
      (no previous offsets to delete)
----------- REGISTRATION
registering 375 frames
Reference frame, 8.82 sec.
Registered second channel in 0.89 sec.
----------- Total 14.78 sec
NOTE: Applying builtin classifier at C:\Users\Dr. Siemens\suite2p\suite2p\classifiers\classifier.npy
----------- ROI DETECTION
Binning movie in chunks of length 10
Binned movie [37,252,254], 0.20 sec.
NOTE: estimated spatial scale ~12 pixels, time epochs 1.00, threshold 10.00
0 ROIs, score=29.97
Found 82 ROIs, 1.50 sec
After removing overlaps, 82 ROIs remain
Masks made in 1.41 sec.
----------- Total 4.77 sec.
----------- EXTRACTION
Extracted fluorescence from 82 ROIs in 375 frames, 0.16 sec.
Extracted fluorescence from 82 ROIs in 375 frames, 0.17 sec.
added enhanced mean image
----------- Total 2.56 sec.
----------- CLASSIFICATION
----------- Total 0.03 sec.
----------- SPIKE DECONVOLUTION
----------- Total 0.00 sec.
Plane 1 processed in 22.16 sec (can open in GUI).
total = 45.67 sec.
Creating combined view
TOTAL RUNTIME 46.02 sec
______________________________________ test_tiff_reconstruction_from_binary_file ______________________________________

test_ops = {'1Preg': False, 'align_by_chan': 1, 'allow_overlap': False, 'aspect': 1.0, ...}

    def test_tiff_reconstruction_from_binary_file(test_ops):
        """
        Tests to see if tif generated by tiff_to_binary and write_tiff matches test tif.
        """
        test_ops['tiff_list'] = ['input.tif']
        op = io.tiff_to_binary(test_ops)
        output_data = get_binary_file_data(op)
        # Make sure data in matrix is nonnegative
        assert np.all(output_data >= 0)
        fname = io.generate_tiff_filename(
            functional_chan=op['functional_chan'],
            align_by_chan=op['align_by_chan'],
            save_path=op['save_path'],
            k=0,
            ichan=True
        )
        io.save_tiff(output_data, fname=fname)
        reconstructed_tiff_data = imread(
            str(Path(test_ops['save_path0']).joinpath('suite2p/plane0/reg_tif/file000_chan0.tif'))
        )
        # Compare to our test data
        prior_data = imread(
            str(Path(test_ops['data_path'][0]).joinpath('1plane1chan/suite2p/test_write_tiff.tif'))
        )
>       assert np.array_equal(reconstructed_tiff_data, prior_data)
E       assert False
E        +  where False = <function array_equal at 0x000001A366864A68>(array([[17419, 16798, 17359, ..., 16303, 16599, 16836],\n       [16485, 16419, 16185, ..., 16830, 16576, 16380],\n      ... [16449, 18001, 16308, ..., 16376, 16613, 17160],\n       [16397, 16393, 16282, ..., 16875, 16649, 17307]], dtype=int16), array([[[17419, 16798, 17359, ..., 16303, 16599, 16836],\n        [16485, 16419, 16185, ..., 16830, 16576, 16380],\n    ...17169, 16806, 17213, ..., 18657, 17320, 17852],\n        [17371, 17063, 16393, ..., 16529, 16294, 16966]]], dtype=int16))
E        +    where <function array_equal at 0x000001A366864A68> = np.array_equal

tests\regression\test_io_pipeline.py:35: AssertionError
------------------------------------------------ Captured stdout call -------------------------------------------------
tif
** Found 1 tifs - converting to binary **
_________________________________________ test_register_binary_do_bidi_output _________________________________________

test_ops = {'1Preg': False, 'Lx': 404, 'Ly': 360, 'align_by_chan': 1, ...}

    def test_register_binary_do_bidi_output(test_ops):
        """
        Regression test that checks the output of register_binary given the `input.tif` with the bidiphase,
        """
        test_ops['do_bidiphase'] = True
        check_registration_output(
            test_ops, (404, 360),
            test_ops['data_path'][0].joinpath('registration/bidi_shift_input.tif'),
            [str(Path(test_ops['save_path0']).joinpath('reg_tif/file000_chan0.tif'))],
>           [str(Path(test_ops['data_path'][0]).joinpath('registration/regression_bidi_output.tif'))]
        )

tests\regression\test_registration_pipeline.py:78:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

op = {'1Preg': False, 'Lx': 404, 'Ly': 360, 'align_by_chan': 1, ...}, dimensions = (404, 360)
input_path = WindowsPath('data/test_data/registration/bidi_shift_input.tif')
reg_output_path_list = ['C:\\Users\\Dr. Siemens\\AppData\\Local\\Temp\\pytest-of-DrSiemens\\pytest-6\\test_register_binary_do_bidi_o0\\reg_tif\\file000_chan0.tif']
output_path_list = ['data\\test_data\\registration\\regression_bidi_output.tif']

    def check_registration_output(op, dimensions, input_path, reg_output_path_list, output_path_list):
        ops = prepare_for_registration(
            op, input_path, dimensions
        )
        reg_ops = []
        npl = op['nplanes']
        for i in range(npl):
            curr_op = register_binary(ops[i])
            registered_data = imread(reg_output_path_list[i*npl])
            output_check = imread(output_path_list[i*npl])
>           assert np.array_equal(registered_data, output_check)
E           assert False
E            +  where False = <function array_equal at 0x000001A366864A68>(array([[17714, 16402, 15995, ..., 17270, 18572, 17432],\n       [16644, 16951, 17429, ..., 17275, 17487, 16757],\n      ... [16888, 16587, 16401, ..., 16285, 17186, 17129],\n       [17428, 16818, 17211, ..., 16332, 16622, 16836]], dtype=int16), array([[[17714, 16402, 15995, ..., 17270, 18572, 17432],\n        [16644, 16951, 17429, ..., 17275, 17487, 16757],\n    ...17060, 16928, 16920, ..., 18051, 17466, 17611],\n        [17684, 17278, 16862, ..., 16923, 16606, 16475]]], dtype=int16))
E            +    where <function array_equal at 0x000001A366864A68> = np.array_equal

tests\regression\test_registration_pipeline.py:60: AssertionError
------------------------------------------------ Captured stdout call -------------------------------------------------
registering 500 frames
NOTE: estimated bidiphase offset from data: -3 pixels
Reference frame, 20.41 sec.
____________________________________ test_register_binary_rigid_registration_only _____________________________________

test_ops = {'1Preg': False, 'Lx': 256, 'Ly': 256, 'align_by_chan': 1, ...}

    def test_register_binary_rigid_registration_only(test_ops):
        """
        Tests that register_binary works for a dataset that only has rigid shifts.
        """
        test_ops['nonrigid'] = False
        op = prepare_for_registration(
            test_ops,
            test_ops['data_path'][0].joinpath('registration/rigid_registration_test_data.tif'),
            (256, 256),
        )[0]
        op = register_binary(op)
        registered_data = imread(str(Path(op['save_path']).joinpath('reg_tif/file000_chan0.tif')))
        # Make sure registered_data is identical across frames
>       check_data = np.repeat(registered_data[0, :, :][np.newaxis, :, :], 500, axis=0)
E       IndexError: too many indices for array

tests\regression\test_registration_pipeline.py:95: IndexError
------------------------------------------------ Captured stdout call -------------------------------------------------
registering 500 frames
Reference frame, 8.89 sec.
________________________________________ test_cli_reg_metrics_runs_with_output ________________________________________

capfd = <_pytest.capture.CaptureFixture object at 0x000001A300199788>
tmpdir = local('C:\\Users\\Dr. Siemens\\AppData\\Local\\Temp\\pytest-of-DrSiemens\\pytest-6\\test_cli_reg_metrics_runs_with0')

    def test_cli_reg_metrics_runs_with_output(capfd, tmpdir):
        os.system(f'reg_metrics data/test_data/ --tiff_list input_1500.tif --do_registration 2 --save_path0 {tmpdir}')
        captured = capfd.readouterr()
>       assert captured.out
E       AssertionError: assert ''
E        +  where '' = CaptureResult(out='', err='usage: reg_metrics [-h] [--single_plane] [--ops OPS] [--db DB] [--version]\r\n             ...cognized arguments: Siemens\\AppData\\Local\\Temp\\pytest-of-DrSiemens\\pytest-6\\test_cli_reg_metrics_runs_with0\r\n').out

tests\smoke\test_cli.py:45: AssertionError
================================================== warnings summary ===================================================
tests/regression/test_full_pipeline.py::test_1plane_1chan_with_batches_metrics_and_exported_to_nwb_format
  C:\Users\Dr. Siemens\Anaconda3\envs\suite2p\lib\site-packages\pynwb\file.py:753: UserWarning: Date is missing timezone information. Updating to local timezone.
    warn("Date is missing timezone information. Updating to local timezone.")

tests/regression/test_full_pipeline.py::test_1plane_1chan_with_batches_metrics_and_exported_to_nwb_format
  C:\Users\Dr. Siemens\Anaconda3\envs\suite2p\lib\site-packages\hdmf\build\objectmapper.py:239: DtypeConversionWarning: Spec 'ImagingPlane/grid_spacing': Value with data type int32 is being converted to data type float32 as specified.
    warnings.warn(full_warning_msg, DtypeConversionWarning)

tests/regression/test_full_pipeline.py::test_mesoscan_2plane_2z
tests/regression/test_full_pipeline.py::test_mesoscan_2plane_2z
tests/regression/test_full_pipeline.py::test_mesoscan_2plane_2z
tests/regression/test_full_pipeline.py::test_mesoscan_2plane_2z
  c:\users\dr. siemens\suite2p\suite2p\registration\register.py:182: UserWarning: number of frames is below 200, unpredictable behaviors may occur.
    warn('number of frames is below 200, unpredictable behaviors may occur.')

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=============================================== short test summary info ===============================================
FAILED tests/regression/test_full_pipeline.py::test_2plane_2chan_with_batches - ValueError: operands could not be bro...
FAILED tests/regression/test_io_pipeline.py::test_tiff_reconstruction_from_binary_file - assert False
FAILED tests/regression/test_registration_pipeline.py::test_register_binary_do_bidi_output - assert False
FAILED tests/regression/test_registration_pipeline.py::test_register_binary_rigid_registration_only - IndexError: too...
FAILED tests/smoke/test_cli.py::test_cli_reg_metrics_runs_with_output - AssertionError: assert ''
================================ 5 failed, 27 passed, 6 warnings in 447.40s (0:07:27) =================================

```

**Comment by nickdelgrosso** [comment] 2020-10-23 09:15
Wow, what is going on here?  If the tests still aren't passing, let's have a one-to-one session and get a suite2p installation onto your machine that passes the tests, so you can safely make contributions.  Feel free to send me an email (on my profile).

**Comment by carsen-stringer** [comment] 2020-11-26 19:50
Thanks Nick for offering to help. I use Windows and Ubuntu 18.04 haven't seen these errors either. I'm going to close this issue for now but let us know if you are still having problems.

**Closed by carsen-stringer** 2020-11-26 19:50 UTC
