### ISSUE TITLE
Can rotations be enabled for manual segmentation?

### ISSUE THREAD

**Issue by diegoasua** [MouseLand/suite2p#590] opened 2020-12-01 18:37 UTC
In the manual labelling mode (which is great for polishing up!) one can create circles and ovals. Although for "prototypical" cortical cells this works well, sometimes said neurons can have morphologies that are oval shaped, but not necessarily oriented in the ordinate axis. If the roi shape could be rotated one could easily fit these non-conventional morphologies.

It would be a matter of adding handles [here](https://github.com/MouseLand/suite2p/blob/6c84f25d0c1629fed7d8a44c4a11631b16979034/suite2p/gui/drawroi.py#L494).

```python
self.ROI.addRotateHandle(pos: List, center: List)
```

This shouldn't otherwise affect the behaviour of the software.

Thanks ahead :brain:!

**Comment by carsen-stringer** [comment] 2021-02-19 02:33
unfortunately it's not that easy, you also need to use the rotation to create the ROI, I tried the built in getArrayRegion function and it doesn't take angle into account, so you have to compute it by hand somehow. if you implement it please submit a pull request and I'll be happy to accept it.

**Comment by camille-lab** [comment] 2021-02-19 09:52
if you press the Alt key when you click the ROI (outline yellow) you can rotate the ellipse with the mouse.
Is this what you were looking for?

**Comment by Moosehorse123** [comment] 2021-03-06 17:35
@camille-lab I'm finding that this does indeed rotate the ellipse in the manual segmentation window, but when looking at the ROI that ultimately gets saved it is not rotated correctly... is anyone seeing this issue as well? Images below 

<img width="695" alt="Screen Shot 2021-03-06 at 12 34 23 PM" src="https://user-images.githubusercontent.com/18012559/110215556-6922dd80-7e78-11eb-99bd-d22e2892081e.png">
<img width="690" alt="Screen Shot 2021-03-06 at 12 33 10 PM" src="https://user-images.githubusercontent.com/18012559/110215563-717b1880-7e78-11eb-8756-efe5e97f8331.png">

**Comment by carsen-stringer** [comment] 2021-07-23 14:29
I had trouble getting that angle info out of pyqtgraph. very happy to accept a pull request on this though if someone wants to dig into the code, but do not plan on adding this myself since it doesn't seem straightforward sorry :(

**Comment by amorsi1** [comment] 2022-02-09 20:48
I'm trying to develop this feature for my lab but want to check if the ROI is a QWidget as it seems unfeasible if it is ([https://stackoverflow.com/questions/58020983/rotate-the-widget-for-some-degree](url). 

If not, I'll try to build an angle system for it

**Comment by cgaletzka** [comment] 2022-04-05 07:03
Could you please let me know if this just an issue with how the rotated ROIs are displayed after the fluorescence traces are extracted? Or can the fluorescence traces actually not be extracted correctly for rotated ROIs?

**Comment by carsen-stringer** [comment] 2023-05-14 02:52
duplicate of #807

**Closed by carsen-stringer** 2023-05-14 02:52 UTC
Labels: enhancement
