### ISSUE TITLE
Analyze longitudinal data

### ISSUE THREAD

**Issue by sarahapark** [MouseLand/suite2p#295] opened 2020-03-02 22:20 UTC
Hello!
Does suite2p now have the ability to analyze longitudinal data? Is there a way to use ROIs from yesterday's data set to analyze today's data set?

Thank you!
Sarah

**Comment by carsen-stringer** [comment] 2020-04-09 18:54
we're hoping to add native support this soon, but in the meantime many users run all of their data at the same time through suite2p (add all the folders across multiple days). Also users use matlab tools that have been written for this: https://github.com/ransona/ROIMatchPub by Adam Ranson

**Comment by catubc** [comment] 2022-01-11 12:45
Hi @sarahapark , any updates on this? We're also trying to match up some longitudinal data individually processed in suite2p.

**Comment by sarahapark** [comment] 2022-01-18 13:46
Hi!
I'm using this MatLab code, ROIMatchPub<https://github.com/ransona/ROIMatchPub>, to align my longitudinal data. It works really well!

Thanks,
Sarah


From: catubc ***@***.***>
Sent: Tuesday, January 11, 2022 7:46 AM
To: MouseLand/suite2p ***@***.***>
Cc: Park, Sarah A ***@***.***>; Mention ***@***.***>
Subject: [External]Re: [MouseLand/suite2p] Analyze longitudinal data (#295)


Hi @sarahapark<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsarahapark&data=04%7C01%7Cparks6%40chop.edu%7C5650597ba7af4e8e91a908d9d5004676%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637775019449565977%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=tMxv9VE%2F2NLWS5btuUHArqua7jxXdG81Ets3vJdBa5I%3D&reserved=0> , any updates on this? We're also trying to match up some longitudinal data individually processed in suite2p.

-
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMouseLand%2Fsuite2p%2Fissues%2F295%23issuecomment-1009930223&data=04%7C01%7Cparks6%40chop.edu%7C5650597ba7af4e8e91a908d9d5004676%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637775019449565977%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gWFrs5Bl06%2B0oWWyK3LXIhp%2FXU%2F7Cor7czRhM0xOmyA%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMLNRROEPM7RPB6ZKLSBWXLUVQQ7JANCNFSM4K753KZA&data=04%7C01%7Cparks6%40chop.edu%7C5650597ba7af4e8e91a908d9d5004676%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637775019449565977%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=O5LS1g9bhjFTcHYdyYxtpXCwNIm9pQ32PZYsqeHNQ8E%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cparks6%40chop.edu%7C5650597ba7af4e8e91a908d9d5004676%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637775019449565977%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OV13qfPhcQSLPvIvdvnHi2Kc6HtHiZ0G%2BR%2BMwwGwJ6k%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cparks6%40chop.edu%7C5650597ba7af4e8e91a908d9d5004676%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637775019449565977%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=RxN0syEibz73TmlAVxVX9WY0v5qGYyIXUZ0TXt0kuAg%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>
** This email originated from an EXTERNAL sender to CHOP. Proceed with caution when replying, opening attachments, or clicking links. Do not disclose your CHOP credentials, employee information, or protected health information to a potential hacker**.

**Comment by catubc** [comment] 2022-01-18 15:29
Hi @sarahapark , yes, we're also testing that code. It's pretty great, except that it's not clear if it works exactly as we expected it. For example, if we set the threshold to 0.6 overlap, it's not clear whether the overlap is 0.6 across all cells or whether it is just for pair-wise cells.   So in one case all matching cells (across 10 sessions, for examples) must have a min 60% overlap with all other possible matching cells. In the other case, every cell has at least one other cell that it overlaps 60%.  As far as we can tell it's the later (much less onerous) than the former.

Any suggestions or comments are welcome.

**Comment by catubc** [comment] 2022-01-19 08:33
Actually, as far as I can see, the algorithm only does pair wise comparisons over time. 

https://github.com/ransona/ROIMatchPub/blob/master/roiMatchPub.m?plain=299.

**Comment by sarahapark** [comment] 2022-01-19 13:51
Hi,
The first experiment is the reference ROI set to which all other data sets are compared.

In the link<https://github.com/ransona/ROIMatchPub/blob/master/roiMatchPub.m?plain=299> you sent, line 150 says, "if it's the first experiment then use it as the comparison point."

Hope this helps!
Sarah

From: catubc ***@***.***>
Sent: Wednesday, January 19, 2022 3:34 AM
To: MouseLand/suite2p ***@***.***>
Cc: Park, Sarah A ***@***.***>; Mention ***@***.***>
Subject: [External]Re: [MouseLand/suite2p] Analyze longitudinal data (#295)


Actually, as far as I can see, the algorithm only does pair wise comparisons over time.

https://github.com/ransona/ROIMatchPub/blob/master/roiMatchPub.m?plain=299<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fransona%2FROIMatchPub%2Fblob%2Fmaster%2FroiMatchPub.m%3Fplain%3D299&data=04%7C01%7Cparks6%40chop.edu%7C2b87864b7a01411d191708d9db2667ee%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637781780266779218%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ApAUXAWsMtNvMlrlb4m1c1tUVp%2FWWaKTA1FO3G1ooQA%3D&reserved=0>.

-
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMouseLand%2Fsuite2p%2Fissues%2F295%23issuecomment-1016200474&data=04%7C01%7Cparks6%40chop.edu%7C2b87864b7a01411d191708d9db2667ee%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637781780266779218%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=dFF%2FBjo556OcOY8fBOb2yvkzZ55x45lZi8Bc117HJgU%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMLNRRPVX4GNW7MYGCA4DJ3UWZZOPANCNFSM4K753KZA&data=04%7C01%7Cparks6%40chop.edu%7C2b87864b7a01411d191708d9db2667ee%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637781780266779218%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=BVZJhxxRYG%2F2RHNxEd7NT9N6jl9Hb%2FwGlXeGJcCUbIw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cparks6%40chop.edu%7C2b87864b7a01411d191708d9db2667ee%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637781780266779218%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=X6aVExHh9OTDiowVhqbnbvChhQmJuA%2B24T1F3OQ5gMc%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cparks6%40chop.edu%7C2b87864b7a01411d191708d9db2667ee%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637781780266779218%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=PxeeZiZcbwPJLWZgweVplVpHYknTuxABA0K0oWFuruI%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>
** This email originated from an EXTERNAL sender to CHOP. Proceed with caution when replying, opening attachments, or clicking links. Do not disclose your CHOP credentials, employee information, or protected health information to a potential hacker**.

**Comment by catubc** [comment] 2022-01-19 13:57
Hi @sarahapark , yes, indeed, the first image is used to compute the projective transformation for all the sessions.

But the issue is re; the cell matching after.  It seems only pairwise comparisons were done, not multi-pairs. I opened an issue with the current repo maintainer. Hopefully they have more insight...

**Comment by sarahapark** [comment] 2022-01-20 15:01
Can you help me understand what kind of multi-pair comparison you are hoping to perform? I know ROIMatchPub does not compare every data set to every other data set in a pair-wise fashion in one ROIMatchPub job. However, this could be done by running multiple ROIMatchPub jobs to compare every data set with every other data set.

To my understanding, when multiple data sets are compared in one ROIMatchPub job, the result is a set of ROIs that match up across all the data sets, based on the 1st data set, which is the reference data set.

Thanks!

From: catubc ***@***.***>
Sent: Wednesday, January 19, 2022 8:58 AM
To: MouseLand/suite2p ***@***.***>
Cc: Park, Sarah A ***@***.***>; Mention ***@***.***>
Subject: [External]Re: [MouseLand/suite2p] Analyze longitudinal data (#295)


Hi @sarahapark<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsarahapark&data=04%7C01%7Cparks6%40chop.edu%7Cf5a05423b7a14179c8ed08d9db53aa25%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637781974659158142%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1Cv8E8JBb9Z479OQmyNreJKwz7WEd4Ca%2BerfHYsMPMA%3D&reserved=0> , yes, indeed, the first image is used to compute the projective transformation for all the sessions.

But the issue is re; the cell matching after. It seems only pairwise comparisons were done, not multi-pairs. I opened an issue with the current repo maintainer. Hopefully they have more insight...

-
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMouseLand%2Fsuite2p%2Fissues%2F295%23issuecomment-1016490398&data=04%7C01%7Cparks6%40chop.edu%7Cf5a05423b7a14179c8ed08d9db53aa25%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637781974659314379%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zgxC4mEOgnrR71rQ6OOX9JirQOT5y2dWT9d3nT8jr9s%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMLNRROTBTSWE2UXAVH3VSLUW27NNANCNFSM4K753KZA&data=04%7C01%7Cparks6%40chop.edu%7Cf5a05423b7a14179c8ed08d9db53aa25%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637781974659314379%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=wPJEW%2FiXQN19wPF%2BE38dR5uutdx8EOxQA7k1oaPcFIo%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cparks6%40chop.edu%7Cf5a05423b7a14179c8ed08d9db53aa25%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637781974659314379%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=THJua0ExyUpH11Tu%2FdBFmlZKgdVQxZv714B3Z0y4dxI%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cparks6%40chop.edu%7Cf5a05423b7a14179c8ed08d9db53aa25%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637781974659314379%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7vgGq0UEv090Q%2BxPDQLRHT38IstOXRdk2mpZrzuVH3w%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>
** This email originated from an EXTERNAL sender to CHOP. Proceed with caution when replying, opening attachments, or clicking links. Do not disclose your CHOP credentials, employee information, or protected health information to a potential hacker**.

**Comment by catubc** [comment] 2022-01-20 15:20
So it is still not clear to us, but as far as we can tell the threshold is only applied in pairwise fashion. 

For example, if you have 3 cells identified across 3 sessions to have a min threshold of 0.5, it could happen that:
- cell1 and cell2 (from sessions 1 and 2 respectively) have = 0.5 overlap 
- cell1 and cell3 have = 0.5 overlap 
- cell2 and cell3 ~= 0.0 overlap 

The code would link these 3 cells as matching, even though cell2 and cell3 were never linked.  So cell1 is linked to cell2 because of their overlap and cell1 and cell3 are linked because of their overlap and that is enough to build a 3-node graph.  But cell2 and cell3 are not linked/overlapping.

To be honest, I'm not sure if this matters for most, but I can see in our datasets that over 5-10 days of recording the drift is substantial and many cells have << 0.5 overlap despite being identified as overlapping.

**Comment by sarahapark** [comment] 2022-01-31 14:42
Hi,
You raise a valid concern regarding drift. I will be analyzing longitudinal data. I will let you know if I notice drift over multiple days of recording so we can compare notes. If there is drift, the code might need to be tweaked. Just fyi. I cannot give you a clear timeline of when I'll have the results since I am starting another round of experiments next week so I have less chunks of time for data analysis. But doing this analysis is definitely high priority, so I'll be in touch.

Thanks!
Sarah

From: catubc ***@***.***>
Sent: Thursday, January 20, 2022 10:20 AM
To: MouseLand/suite2p ***@***.***>
Cc: Park, Sarah A ***@***.***>; Mention ***@***.***>
Subject: [External]Re: [MouseLand/suite2p] Analyze longitudinal data (#295)


So it is still not clear to us, but as far as we can tell the threshold is only applied in pairwise fashion.

For example, if you have 3 cells identified across 3 sessions to have a min threshold of 0.5, it could happen that:

  *   cell1 and cell2 (from sessions 1 and 2 respectively) have = 0.5 overlap
  *   cell1 and cell3 have = 0.5 overlap
  *   cell2 and cell3 ~= 0.0 overlap

The code would link these 3 cells as matching, even though cell2 and cell3 were never linked. So cell1 is linked to cell2 because of their overlap and cell1 and cell3 are linked because of their overlap and that is enough to build a 3-node graph. But cell2 and cell3 are not linked/overlapping.

To be honest, I'm not sure if this matters for most, but I can see in our datasets that over 5-10 days of recording the drift is substantial and many cells have << 0.5 overlap despite being identified as overlapping.

-
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMouseLand%2Fsuite2p%2Fissues%2F295%23issuecomment-1017615661&data=04%7C01%7Cparks6%40chop.edu%7C96ccf6b95ebb4189b77e08d9dc285b84%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637782888162190571%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=LqEf9hIC67vv4Mm%2Btmap1Pr1fEnDmWFwbSEWFtb5BfM%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMLNRRMHW2MDQHXPBF2UUYDUXAR2ZANCNFSM4K753KZA&data=04%7C01%7Cparks6%40chop.edu%7C96ccf6b95ebb4189b77e08d9dc285b84%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637782888162190571%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Fnra5HuZ7wsd%2BnHAl3RKy8S6ns1mKjyNwX0WCcSFhwY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cparks6%40chop.edu%7C96ccf6b95ebb4189b77e08d9dc285b84%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637782888162190571%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cKsm0LI6WSe8z0ZA1C7Toj4IyNx1QoM0VCXVRGM4Cjo%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cparks6%40chop.edu%7C96ccf6b95ebb4189b77e08d9dc285b84%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637782888162190571%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=anO8x%2BkobCLT5AYJY5O5MVo7%2FLbsqrjxkcINP6gnpRI%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>
** This email originated from an EXTERNAL sender to CHOP. Proceed with caution when replying, opening attachments, or clicking links. Do not disclose your CHOP credentials, employee information, or protected health information to a potential hacker**.

**Comment by catubc** [comment] 2022-02-02 07:53
Thanks @sarahapark , keep me posted.
FYI: I'm testing https://github.com/zivlab/CellReg and this tool seems to recover many more cells the ROIMatchPub. It's also completely unsupervised, which is a huge advantage.
Best

**Comment by sarahapark** [comment] 2022-02-03 14:42
Hi,
Please let me know how CellReg compares to ROIMatchPub! If I get the chance, I'll check out CellReg too.

Thanks!

From: catubc ***@***.***>
Sent: Wednesday, February 2, 2022 2:54 AM
To: MouseLand/suite2p ***@***.***>
Cc: Park, Sarah A ***@***.***>; Mention ***@***.***>
Subject: [External]Re: [MouseLand/suite2p] Analyze longitudinal data (#295)


Thanks @sarahapark<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsarahapark&data=04%7C01%7Cparks6%40chop.edu%7C3e8034e74ee44232391208d9e6211efe%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637793852214798769%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=46pGHUU08Rwv7Di5hyp%2FXKJqG6FWBbYmt2Gtj9lIvnE%3D&reserved=0> , keep me posted.
FYI: I'm testing https://github.com/zivlab/CellReg<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fzivlab%2FCellReg&data=04%7C01%7Cparks6%40chop.edu%7C3e8034e74ee44232391208d9e6211efe%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637793852214798769%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=S9YpSCiqfWUncivGylS5fy7LRg00uyhIEg8oKnX%2BJAU%3D&reserved=0> and this tool seems to recover many more cells the ROIMatchPub. It's also completely unsupervised, which is a huge advantage.
Best

-
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMouseLand%2Fsuite2p%2Fissues%2F295%23issuecomment-1027670660&data=04%7C01%7Cparks6%40chop.edu%7C3e8034e74ee44232391208d9e6211efe%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637793852214798769%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=y1JBXXuAk9rENYsT0%2B%2F7d%2Fm6pFPD5uJaE7r4RpCuxBg%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMLNRRJ6RNHD7HWHZ2URJ6LUZDPIBANCNFSM4K753KZA&data=04%7C01%7Cparks6%40chop.edu%7C3e8034e74ee44232391208d9e6211efe%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637793852214798769%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=971EGyjd5P01Y3DORwFLGPkc5%2Fe%2BvpYGvTHSktfs56s%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cparks6%40chop.edu%7C3e8034e74ee44232391208d9e6211efe%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637793852214798769%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=he3Si5J9WhWg9DIwAy3yKzlfMXQshauXHK%2BTUlDV%2Fw8%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cparks6%40chop.edu%7C3e8034e74ee44232391208d9e6211efe%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637793852214798769%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mf8eIfB0ZP1LXGhqCj0Tj%2BIe566bOtxX44cqbRDY1OI%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>
** This email originated from an EXTERNAL sender to CHOP. Proceed with caution when replying, opening attachments, or clicking links. Do not disclose your CHOP credentials, employee information, or protected health information to a potential hacker**.

**Comment by catubc** [comment] 2022-02-07 13:26
Hi Sarah
I only had time to do one dataset matching. The dataset had 3 sessions (recorded on 3 sequential days).

CellReg matched ~480 cells, whereas ROIMatchPub recovered ~150 cells (and even if I used my own python code which used convex hull overlaps, I still only got ~220 cells).  

https://github.com/zivlab/CellReg/issues/12

Give that CellReg is a published method and it's unsupervised, we're planning on using it exclusively going forward (unless/until other problems arise).

PM me if you have questions, but the Liron is very responsive and supportive.

Good luck

**Comment by carsen-stringer** [comment] 2023-05-14 02:49
duplicate of #933

**Closed by carsen-stringer** 2023-05-14 02:49 UTC
Labels: enhancement
