### ISSUE TITLE
Error in saving .mat file (after updating to newest version of Suite2p)

### ISSUE THREAD

**Issue by RichieHakim** [MouseLand/suite2p#533] opened 2020-09-10 23:18 UTC
I used to use v0.6.16 (and never had this or any issues) before upgrading to v0.9.0 (what I have currently). I now get an error at the end of a run when it tries to save to a .mat file. I receive the error pasted below. When I try to save as mat using the GUI with the loaded data, it does not save a GUI (though the conda prompt does display 'saving to mat', no mat file is saved in the directory).
Any help would be greatly appreciated.

Using Windows 7. Intel i7-5930K. 64GB memory

.
.
.
Registered 98000/102932 in 9115.56s
Registered 100000/102932 in 9301.67s
Registered 102000/102932 in 9487.96s
----------- Total 9639.46 sec
Registration metrics, 48.18 sec.
NOTE: applying default C:\Users\Lab\.suite2p\classifiers\classifier_user.npy
----------- ROI DETECTION
Binning movie in chunks of length 21
Binned movie [4715,488,1004], 464.27 sec.
NOTE: estimated spatial scale ~12 pixels, time epochs 3.93, threshold 39.29 
0 ROIs, score=982.24
1000 ROIs, score=108.66
2000 ROIs, score=80.66
3000 ROIs, score=64.75
4000 ROIs, score=53.19
Found 5000 ROIs, 398.83 sec
After removing overlaps, 4847 ROIs remain
Masks made in 70.43 sec.
----------- Total 936.32 sec.
----------- EXTRACTION
Extracted fluorescence from 4847 ROIs in 102932 frames, 1908.13 sec.
added enhanced mean image
----------- Total 2038.26 sec.
----------- CLASSIFICATION
----------- Total 0.06 sec.
----------- SPIKE DECONVOLUTION
----------- Total 28.92 sec.
>>>ERROR<<<
Traceback (most recent call last):
  File "F:\RH_Local\Anaconda\envs\suite2p\lib\runpy.py", line 193, in _run_module_as_main
>>>ERROR<<<
    "__main__", mod_spec)
  File "F:\RH_Local\Anaconda\envs\suite2p\lib\runpy.py", line 85, in _run_code
>>>ERROR<<<
    exec(code, run_globals)
  File "F:\RH_Local\Anaconda\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 78, in <module>
>>>ERROR<<<
    main()
  File "F:\RH_Local\Anaconda\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 71, in main
    run_s2p(ops, db)
  File "F:\RH_Local\Anaconda\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 398, in run_s2p
>>>ERROR<<<
    op = run_plane(op, ops_path=ops_path)
  File "F:\RH_Local\Anaconda\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 278, in run_plane
    'iscell': np.load(os.path.join(fpath, 'iscell.npy'))
  File "F:\RH_Local\Anaconda\envs\suite2p\lib\site-packages\scipy\io\matlab\mio.py", line 285, in savemat
>>>ERROR<<<
    MW.put_variables(mdict)
  File "F:\RH_Local\Anaconda\envs\suite2p\lib\site-packages\scipy\io\matlab\mio5.py", line 849, in put_variables
>>>ERROR<<<
    self._matrix_writer.write_top(var, asbytes(name), is_global)
  File "F:\RH_Local\Anaconda\envs\suite2p\lib\site-packages\scipy\io\matlab\mio5.py", line 590, in write_top
>>>ERROR<<<
    self.write(arr)
  File "F:\RH_Local\Anaconda\envs\suite2p\lib\site-packages\scipy\io\matlab\mio5.py", line 619, in write
>>>ERROR<<<
    self.write_struct(narr)
  File "F:\RH_Local\Anaconda\envs\suite2p\lib\site-packages\scipy\io\matlab\mio5.py", line 738, in write_struct
    self._write_items(arr)
  File "F:\RH_Local\Anaconda\envs\suite2p\lib\site-packages\scipy\io\matlab\mio5.py", line 755, in _write_items
    self.write(el[f])
  File "F:\RH_Local\Anaconda\envs\suite2p\lib\site-packages\scipy\io\matlab\mio5.py", line 629, in write
    self.write_numeric(narr)
  File "F:\RH_Local\Anaconda\envs\suite2p\lib\site-packages\scipy\io\matlab\mio5.py", line 655, in write_numeric
>>>ERROR<<<
    self.write_element(arr)
  File "F:\RH_Local\Anaconda\envs\suite2p\lib\site-packages\scipy\io\matlab\mio5.py", line 496, in write_element
    self.write_regular_element(arr, mdtype, byte_count)
  File "F:\RH_Local\Anaconda\envs\suite2p\lib\site-packages\scipy\io\matlab\mio5.py", line 510, in write_regular_element
    tag['byte_count'] = byte_count
OverflowError: Python int too large to convert to C long
Interrupted by error (not finished)

**Comment by nickdelgrosso** [comment] 2020-09-18 12:13
Looks like it's related to a scipy matlab file saving bug: https://stackoverflow.com/questions/38314118/overflowerror-python-int-too-large-to-convert-to-c-long-on-windows-but-not-ma

**Comment by nickdelgrosso** [comment] 2020-09-18 12:19
Trying to track this down now -- can you confirm @RichieHakim whether the "iscell.npy" was written by the same version of suite2p and the same computer as the suite2p version and computer that is reading it?

**Comment by nickdelgrosso** [comment] 2020-09-18 12:35
Duplicate of this issue: https://github.com/MouseLand/suite2p/issues/533

**Closed** 2020-09-18 12:36 UTC
Labels: bug, duplicate
