### ISSUE TITLE
Problems merging ROIs. Also trying to visualize ROI correlations

### ISSUE THREAD

**Issue by maristanye** [MouseLand/suite2p#652] opened 2021-04-06 17:06 UTC
Hi, first of all thanks for the amazing software. Here is my problem (suite2p version 0.10.0; but also in 0.9.0):
**When trying to merge manually ROIs in the GUI nothing happens and the terminal says:**
merging activity... this may take some time
Traceback (most recent call last):
  File "c:\users\emc34\anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\gui2p.py", line 269, in keyPressEvent
    merge.do_merge(self)
  File "c:\users\emc34\anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\merge.py", line 31, in do_merge
    merge_activity_masks(parent)
  File "c:\users\emc34\anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\merge.py", line 58, in merge_activity_masks
    if len(parent.stat[n]['imerge']) > 0:
KeyError: 'imerge'

**When trying to do this with the autosuggest:**
creating merge window... this may take some time
Traceback (most recent call last):
  File "c:\users\emc34\anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\menus.py", line 149, in <lambda>
    parent.sugMerge.triggered.connect(lambda: suggest_merge(parent))
  File "c:\users\emc34\anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\menus.py", line 190, in suggest_merge
    MergeWindow = merge.MergeWindow(parent)
  File "c:\users\emc34\anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\merge.py", line 241, in __init__
    self.CC  = np.matmul(parent.Fbin[parent.iscell], parent.Fbin[parent.iscell].T) / parent.Fbin.shape[-1]
AttributeError: 'MainWindow' object has no attribute 'Fbin'

**Apart from that, when trying to visualize the ROI color by the correlation to each other (K: correlations,bin) the GUI gets stuck and I get:**
Traceback (most recent call last):
  File "c:\users\emc34\anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\masks.py", line 561, in <lambda>
    self.clicked.connect(lambda: self.press(parent, bid))
  File "c:\users\emc34\anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\masks.py", line 582, in press
    parent.update_plot()
  File "c:\users\emc34\anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\gui2p.py", line 371, in update_plot
    masks.corr_masks(self)
  File "c:\users\emc34\anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\masks.py", line 400, in corr_masks
    sn = parent.Fbin[n].mean(axis=-2).squeeze()
AttributeError: 'MainWindow' object has no attribute 'Fbin'

thanks in advance

**Comment by carsen-stringer** [comment] 2021-07-23 10:29
is this fixed now? closing for now because I can't reproduce the error, the GUI not having "Fbin" sounds like the plane didn't load correctly at all?

**Closed by carsen-stringer** 2021-07-23 10:29 UTC
Labels: bug
