### ISSUE TITLE
FEATURE: Allow loading of NWB files with image data

### ISSUE THREAD

**Issue by rly** [MouseLand/suite2p#931] opened 2023-03-08 09:09 UTC
### Feature you'd like to see:

I would like to see "nwb" added as an input format in the  "Run suite2p" GUI.

On selection of NWB, the user should be prompted for the name of the TwoPhotonSeries object to look for in the acquisition group of the NWB file. Then, because NWB files are HDF5 files, suite2p can proceed as if it were reading an h5 file, where the data path is at "/acquisition/\<user-entered name of group\>/data".

### Attempted alternative approaches:

I can rename the NWB file and change the extension from .nwb to .h5. Then run suite2p with the data path as "/acquisition/TwoPhotonSeries/data" which works for [dandiset 54](https://dandiarchive.org/dandiset/000054)

### Additional Context

I could try to help with this.

**Comment by carsen-stringer** [comment] 2023-05-14 01:49
hi @rly, we can change it so that suite2p looks for the *.nwb extension in a folder. happy to take a pull request on this if there's more work than this needed

**Comment by carsen-stringer** [comment] 2023-05-14 02:29
duplicate of #746

**Closed by carsen-stringer** 2023-05-14 02:29 UTC
Labels: enhancement
