### ISSUE TITLE
Colormap changes 

### ISSUE THREAD

**Issue by horsto** [MouseLand/suite2p#225] opened 2019-08-21 13:01 UTC
I just noticed that switching between ROI view (typing "Q") and  Max projection ("T") while color coding for "J" (classifier) changes the colormap (see screenshots below). 
(I didn't pull any changes since https://github.com/MouseLand/suite2p/commit/90a701c6e364d8095c305253192dd43aa2546738 - so sorry if this was already fixed (?)) 

![Screenshot 2019-08-21 at 14 53 53](https://user-images.githubusercontent.com/7548928/63433675-ed8f4600-c423-11e9-82cd-7247939b2e5b.png)
![Screenshot 2019-08-21 at 14 53 59](https://user-images.githubusercontent.com/7548928/63433676-ed8f4600-c423-11e9-98b5-22c5b0c92974.png)

**Comment by carsen-stringer** [comment] 2019-08-30 15:16
hmm I can't reproduce this - maybe a weird bug with having the red channel too

**Comment by carsen-stringer** [comment] 2019-11-16 22:15
I've rewritten the gui layers to hopefully not be as buggy. I am going to close this, please reopen if you're still having issues

**Closed by carsen-stringer** 2019-11-16 22:15 UTC
